<!-- include for Climate Change Conference, September 2008 -->
<div>

<p class=MsoNormalCenter><b><span style='font-size:22.0pt'>Climate Change and Systematics</span></b></p>

<p class=MsoNormalCenter16><b>1<sup>st</sup> - 3<sup>rd</sup> September 2008</b></p>

<p class=MsoNormalCenter16><b>Call for oral and poster presentations</b></p>

<p class=MsoNormalSpacer>&nbsp;</p>

<p class=MsoNormalCenter16><img width=260 height=400 src="/events/namib-desert-v-49a.jpg" 
alt="Dead Acacia Tree and sun in Hidden Vlei pan, Namib Desert, Namibia: &copy; Frantisek Staud/www.phototravels.net" 
title="Dead Acacia Tree and sun in Hidden Vlei pan, Namib Desert, Namibia: &copy; Frantisek Staud/www.phototravels.net"></p>

<p class=MsoNormalSpacer>&nbsp;</p>

<p class=MsoNormalCenter16><b>A meeting organised by the</b></p>

<p class=MsoNormalSpacer>&nbsp;</p>

<p class=MsoNormalCenter16>Department of Botany, School of Natural Sciences, Trinity College Dublin, Ireland</p>

<p class=MsoNormalSpacer>&nbsp;</p>

<p class=MsoNormalCenter16>on behalf of the Systematics Association</p>

<p class=MsoNormalCenter16>and the Linnean Society</p>

<p class=MsoNormalSpacer>&nbsp;</p>

<!-- margin-left: auto; margin-right: auto; float: none;  -->
<div style="display: block; background-color: #ffffff; text-align: center;">
<img src="/images/TCD-Logo1.jpg" width="76" height="100" alt="Trinity College Dublin" title="Trinity College Dublin">
<img src="/images/TCD-Logo2.jpg" width="86" height="100" alt="Botany Department, Trinity College Dublin" title="Botany Department, Trinity College Dublin">
<img src="/images/SystAssLogo-100.png" width="81" height="100" alt="Systematics Association" title="Systematics Association">
<img src="/images/LinnSocLogo-100.jpg" width="77" height="100" alt="Linnean Society of London" title="Linnean Society of London">
</div>

<p class=MsoNormalSpacer>&nbsp;</p>

<div style="background-color: #cc6633">
<p class=MsoNormalCenter16>Please <a href="/events/ClimateChange1stFlier.pdf" rel="external">download</a> a flier with further details</p>
</div>

<p class=MsoNormalSpacer>&nbsp;</p>

<p class=MsoNormalSubHead>To receive subsequent circulars and participate in the meeting</p>

<p class=MsoNormal>Please complete the form available at <a href="http://www.tcd.ie/botany/" rel="external">http://www.tcd.ie/botany/</a> and return by email to:</p>

<p class=MsoNormal><strong>Email:</strong> <a href="mailto:climate@tcd.ie">climate@tcd.ie</a></p>

<p class=MsoNormal><strong>Subject:</strong> conference form</p>

<p class=MsoNormalSpacer>&nbsp;</p>

<p class=MsoNormalSubHead>Organising Committee</p>

<p class=MsoNormal><strong><span style='font-size:10.0pt'>T. Hodkinson, M. Jones, J. Parnell, S. N&iacute; Sheoin, S. Waldren</span></strong></p>

<p class=MsoNormal><strong>Email:</strong> <a href="mailto:climate@tcd.ie">climate@tcd.ie</a></p>

<p class=MsoNormal><strong>Address:</strong> Department of Botany, Trinity College Dublin, Dublin 2, Ireland</p>

<p class=MsoNormal><strong>Fax:</strong> +353-1-8961147</p>

<p class=MsoNormal><strong>Phone:</strong> +353-1-8961274</p>

</div>
