<div class=Section1>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:28.0pt'>Climate Change and Systematics</span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:18.0pt'>1<sup>st</sup> - 3<sup>rd</sup> September 2008</span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:18.0pt'>Call for oral and poster presentations</span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:18.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:18.0pt'><img width=260 height=400 src="/events/namib-desert-v-49a.jpg" 
alt="Namib Desert, Namibia: &copy; Frantisek Staud/www.phototravels.net" 
title="Namib Desert, Namibia: &copy; Frantisek Staud/www.phototravels.net"></span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:18.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:18.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:18.0pt'>A meeting organised by the</span></b></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:18.0pt'>&nbsp;</span></b></p>

<p class=MsoBodyText><span lang=EN-US>Department of Botany, School of Natural
Sciences, Trinity College Dublin, Ireland</span></p>

<p class=MsoBodyText><span lang=EN-US>&nbsp;</span></p>

<p class=MsoBodyText><span lang=EN-US>on behalf of the Systematics Association</span></p>

<p class=MsoBodyText><span lang=EN-US>and the Linnean Society</span></p>

<b><span lang=EN-US style='font-size:18.0pt;font-family:"Comic Sans MS"'><br
clear=all style='page-break-before:always'>
</span></b>

<p class=MsoNormal style='text-align:justify'><b><u><span lang=EN-US>Climate
Change and Systematics</span></u></b></p>

<p class=MsoNormal style='text-align:justify'><span lang=GA style='font-size: 9.0pt'>
This meeting, organised on behalf of the Systematics Association and the
Linnean Society, will provide a forum for systematists to present and discuss
their research as it relates to the critical issue of Global Climate Change.
The conference is open to everyone, whatever their chosen discipline within
systematics.</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=GA style='font-size:
9.0pt'>&nbsp;</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>The meeting will examine the problems posed by Global
Climate Change and will centre on three themes: 1. Climate change and
speciation/extinction; 2. Climate change and biogeography; 3. Climate change:
documenting and conserving biodiversity.</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>&nbsp;</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>We feel this meeting is timely because of the interest
in this topic at all levels in society, especially governmental. For example,
the Millennium Ecosystem Assessment states that '<i><span style='color:black'>By
the end of the twenty-first century, climate change and its impacts may be the
dominant direct driver of biodiversity loss and changes in ecosystem services
globally'</span></i> and '<i><span style='color:black'>Historically, habitat
and land use change have had the biggest impact on biodiversity across biomes.
Climate change is projected to increasingly affect all aspects of biodiversity,
from individual organisms, through populations and species, to ecosystem
composition and function</span></i><span style='color:black'>'.</span></span><span
lang=EN-US style='font-size:9.0pt;font-family:Arial-Black;color:black'> </span><span
lang=EN-US style='font-size:9.0pt'>The most recent IPCC report this year also
highlights these issues. Therefore, global climate change needs to be addressed
holistically by the systematics community.</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>&nbsp;</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>Certainly, the changes in the density and location of
the World's biodiversity are likely to have impacts on speciation/extinction
rates and on the ability of systematists to delimit, through Monographs, Faunas
and Floras, the World’s biodiversity.</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>&nbsp;</span></p>

<p class=MsoNormal style='text-align:justify'><b><u><span lang=EN-US>Speakers
and call for oral and poster presentations</span></u></b></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>A provisional list of invited speakers who have so far
agreed to participate includes: Professor Richard Bateman (Biosciences
Federation), Professor Pieter Baas (National Herbarium of the Netherlands), 
Professor Henrik Balslev (University of Aarhus), Professor Michael Donoghue (Yale
University), Dr. Felix Forest (Royal Botanic Garden Kew), Professor Brian
Huntley, (University of Durham), Dr. Jenny McElwain (University College
Dublin), Dr. Peter Mayhew (University of York), Professor </span><span
lang=EN-US style='font-size:9.0pt'>Josep </span><span lang=EN-US
style='font-size:9.0pt'>Pe&ntilde;uelas, (University of Barcelona), Dr. David Simpson
(Royal Botanic Gardens Kew), Dr. Tim Sparks (NERC Centre for Ecology and
Hydrology), Professor Ian Woodward (University of Sheffield), Dr. Peter Wyse
Jackson (National Botanic Gardens, Glasnevin). If you wish to submit an oral
paper or poster then please fill in the form at the end of the 'First Circular
and Form' document - available at <b><a href="http://www.tcd.ie/botany/"><span
style='color:windowtext;text-decoration:none'>http://www.tcd.ie/botany/</span></a></b>
and return as outlined below.</span></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>&nbsp;</span></p>

<h2><span lang=EN-US>To receive subsequent circulars and participate in the
meeting</span></h2>

<p class=MsoNormal><span lang=EN-US style='font-size:9.0pt'>Please complete the
form available at <a href="http://www.tcd.ie/botany/"><span style='color:windowtext;
text-decoration:none'>http://www.tcd.ie/botany/</span></a> and return by email
to:</span></p>

<p class=MsoNormal><b><span lang=EN-US style='font-size:9.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal><b><span lang=EN-US style='font-size:9.0pt'>Email:</span></b>
<span lang=EN-US style='font-size:9.0pt'><a href="mailto:climate@tcd.ie"><span style='color:
windowtext;text-decoration:none'>climate@tcd.ie</span></a></span></p>

<p class=MsoNormal><b><span lang=EN-US style='font-size:9.0pt'>Subject:</span></b><span
lang=EN-US style='font-size:9.0pt'>conference form</span></p>

<p class=MsoNormal align=center style='text-align:center'><b><span lang=EN-US
style='font-size:10.0pt'>&nbsp;</span></b></p>

<p class=MsoNormal style='text-align:justify'><b><u><span lang=EN-US>Please
note</span></u></b></p>

<p class=MsoNormal style='text-align:justify'><span lang=EN-US
style='font-size:9.0pt'>To ensure that you know that we have received your
emailed booking form you will receive an email reply from us confirming its
receipt. If you do not receive such confirmation then we have not received your
form. In this case, please try again, or post it directly to: Climate Change
&amp; Systematics Conference, Botany Department, Trinity College Dublin, Dublin
2, Ireland no later than 20<sup>th</sup> February 2008.</span></p>

<p class=MsoNormal style='text-align:justify'><b><span lang=EN-US
style='font-size:9.0pt'>&nbsp;</span></b></p>

<h2><span lang=EN-US>Contact</span></h2>

<p class=MsoNormal><span lang=EN-US style='font-size:9.0pt'>Email:</span><span
lang=EN-US style='font-size:9.0pt'><a href="mailto:climate@tcd.ie"><span
style='color:windowtext;text-decoration:none'>climate@tcd.ie</span></a></span></p>

<p class=MsoNormal><span lang=EN-US style='font-size:9.0pt'>Address: Department of 
Botany, Trinity College Dublin, Dublin 2, Ireland</span></p>

<p class=MsoNormal><span lang=EN-US style='font-size:9.0pt;color:black'>Fax: +353-1-8961147</span></p>

<p class=MsoNormal><span lang=EN-US style='font-size:9.0pt;color:black'>Phone: +353-1-8961274</span></p>

<p class=MsoNormal style='margin-top:12.0pt;text-align:justify'><b><span
lang=EN-US style='font-size:10.0pt'>T. Hodkinson, M. Jones, J. Parnell, S. N&iacute; Sheoin, 
S. Waldren (Organising Committee)</span></b></p>

</div>
