Workshop on Molecular Evolution, Europe 2010
Cesky Krumlov, Czech Republic

10 - 22 January 2010, individual research session 22 - 29 January 2010

Application Deadline: 1 October 2009

http://workshop.molecularevolution.org/

Michael P. Cummings and Scott A. Handley, Co-Directors Naiara 
Rodriquez-Ezpeleta, Associate Director

The Workshop on Molecular Evolution has been the finest course on the 
subject since first offered in 1988 in Woods Hole, USA. The Workshop 
will again be offerred in Europe, in January 2010. The Workshop 
consists of a series of lectures, demonstrations and computer 
laboratories that cover various aspects of molecular evolution. 
Faculty are chosen exclusively for their effectiveness in teaching 
theory and practice in molecular evolution. Included among the faculty 
are developers and other experts in the use of computer programs and 
packages such as BLAST, BEAST, Clustal W and Clustal X, FASTA, 
FigTree, Genealogical Sorting Index, GARLI, LAMARC, MAFFT, Migrate-N, 
MrBayes, PAML, PAUP*, and SeaView who provide demonstrations and 
consultations.

The course is designed for established investigators, postdoctoral 
scholars, and advanced graduate students with prior experience in 
molecular evolution and related fields. Scientists with strong 
interests in molecular evolution, phylogenetics, population genetics, 
and related fields are encouraged to apply for admission.
Scheduled  lectures and computer laboratories total ~90 hours of 
instruction. An optional all-computer laboratory of 54+ hours of 
independent work with guidance and consultation of some faculty and 
teaching assistants is offered during the third week. Admission is 
limited and highly competitive, with admissions decisions determined 
by an international committee.

Topics to be covered include:

  - Databases and sequence matching: database searching: protein 
sequence versus protein structure; homology; mathematical, 
statistical, and theoretical aspects of sequence database searches
  - Phylogenetic analysis: theoretical, mathematical and statistical 
bases; sampling properties of sequence data; Bayesian analysis; 
hypothesis testing
  - Maximum likelihood theory and practice in phylogenetics and 
population genetics: coalescent theory; maximum likelihood estimation 
of population genetic parameters
	- Molecular evolution integrated at organism and higher levels:  
population biology; biogeography; ecology; systematics and 
conservation; population genetics
	- Molecular evolution and development: gene duplication and 
divergence; gene family organization; coordinated expression in 
evolution
	- Comparative genomics: genome content; genome structure; genome 
evolution
	- Molecular evolution of recently diverged species

2010 Fee: 1800 USD, plus an additional 750 USD for the highly 
recommended, but optional, third week of all-computer laboratory for 
work on your own data with guidance and consultation of some faculty 
and teaching assistants. Fees include opening reception and mid- 
course dinner,  but do not include other meals or housing. Special 
discounted pricing has been arranged for hotels, pensions and hostels.

For more information and online application see the Workshop web site 
-
http://workshop.molecularevolution.org/

The Workshop on Comparative Genomics is also being offered immediately 
following the Workshop on Molecular Evolution.

______________________________________________________________________

Workshop on Comparative Genomics, Europe 2010

Cesky Krumlov, Czech Republic

24 January - 5 February 2010

Application Deadline: 1 October 2009

http://workshop.molecularevolution.org/

Michael P. Cummings and Scott A. Handley, Co-Directors Naiara 
Rodriquez-Ezpeleta, Associate Director

The Workshop on Comparative Genomics consists of a series of lectures, 
demonstrations and computer laboratories that cover various aspects of 
comparative genomics. Faculty are chosen exclusively for their 
effectiveness in teaching theory and practice in comparative genomics. 
Included among the faculty are developers and other experts in the use 
of computer programs and packages such as Ensembl, Galaxy, and Species 
Assignment Package who provide demonstrations and consultations. The 
course is designed for established investigators, postdoctoral 
scholars, and advanced graduate students. Scientists with strong 
interests in the uses of short-read sequence data, analytical methods, 
comparative structure of genomes, SNP detection and analysis, CNV, 
genome visualization tools and related areas are encouraged to apply 
for admission.
Lectures and computer laboratories total ~90 hours of scheduled 
instruction. Admission is limited and highly competitive, with 
admissions decisions determined by an international committee.

Topics to be covered include:

	- Sequencing technologies: short-read sequencing technologies of 
various types
	- Assembly and alignment: basic analyses in de novo and resequencing 
studies
	- Gene finding and annotation: functional description of genomic data
	- Genome characterization: gene content; genome structure; synteny; 
SNPs; copy number variation (CNV)
	- Assigning sequences to taxonomic groups in metagenomic studies:  
moving from sequences of unknown taxa to known taxa

2010 Fee: 2250 USD. Fee include opening reception and mid-course 
dinner, but does not include other meals or housing. Special 
discounted pricing has been arranged for hotels, pensions and hostels.

For more information and online application see the Workshop web site 
-
http://workshop.molecularevolution.org/

The Workshop on Molecular Evolution is also being offered immediately 
before the Workshop on Comparative Genomics.

Dr Andrea Waeschenbach
DC1 712
Department of Zoology
The Natural History Museum
Cromwell Road, London SW7 5BD, UK
Tel: +44 (0) 207 942 6114 or 5008
Fax: +44 (0) 207 942 5151

