<p>Workshop on Molecular Evolution, Europe 2011</p>

<p>Cesky Krumlov, Czech Republic</p>

<p>23 January - 4 February 2011, individual research session 4 - 11 February 2011</p>


<p><strong>Application Deadline: 1 October 2010</strong></p>

<p><a href="http://www.molecularevolution.org/workshops/WME">http://www.molecularevolution.org/workshops/WME</a></p>

<p>Michael P. Cummings, Scott A. Handley and Naiara Rodriquez-Ezpeleta Co-Directors</p>

<p>The Workshop consists of a series of lectures, demonstrations and computer laboratories 
that cover various aspects of molecular evolution. Faculty are chosen exclusively 
for their effectiveness in teaching theory and practice in molecular evolution. Included 
among the faculty are developers and other experts in the use of computer programs 
and packages such as BLAST, BEAST, Clustal W and Clustal X, FASTA, FigTree, Genealogical 
Sorting Index, GARLI, LAMARC, MAFFT, Migrate-N, MrBayes, PAML, PAUP*, and SeaView 
who provide demonstrations and consultations.</p>

<p>The course is designed for established investigators, postdoctoral scholars, and 
advanced graduate students with prior experience in molecular evolution and related 
fields. Scientists with strong interests in molecular evolution, phylogenetics, population 
genetics, and related fields are encouraged to apply for admission. Scheduled lectures 
and computer laboratories total ~90 hours of instruction. An optional all-computer 
laboratory of 54+ hours of independent work with guidance and consultation of some 
faculty and teaching assistants is offered during the third week. Admission is limited 
and highly competitive, with admissions decisions determined by an international committee.</p>

<p>Topics to be covered include:</p>

<ul>
<li>Protein evolution and database searching: protein sequence versus protein structure; homology; mathematical, statistical, and theoretical aspects of sequence database searches</li>
<li>Phylogenetic analysis: theoretical, mathematical and statistical bases; sampling properties of sequence data; Bayesian analysis; hypothesis testing</li>
<li>Maximum likelihood and Bayesian theory and practice in phylogenetics and population genetics: coalescent theory; estimation of population genetic parameters</li>
<li>Molecular evolution integrated at organism and higher levels: population biology; biogeography; ecology; systematics and conservation; population genetics</li>
<li>Detecting positive selection: theory and practice; codon models</li>
<li>Dating phylogenies: theory and practice</li>
<li>Molecular evolution of recently diverged species</li>
</ul>

<p>2011 Fee: 1800 USD, plus an additional 750 USD for the highly recommended, but optional, third week of all-computer laboratory for work on your own data with guidance and consultation of some faculty and teaching assistants. Fees include opening reception and mid-course dinner, but do not include other meals or housing. Special discounted pricing has been arranged for hotels, pensions and hostels.</p>

<p>For more information and online application see the Workshop web site -</p>

<p><a href="http://www.molecularevolution.org/workshops/WME">http://www.molecularevolution.org/workshops/WME</a></p>

<p>The Workshop on Comparative Genomics is also being offered immediately before 
the Workshop on Molecular Evolution, see http://www.molecularevolution.org/workshops/WCG</p>
