<p>Applications are invited from all nationalities for ten student bursaries, funded 
by the conference organisers. The bursaries will cover the cost of registration, 
conference dinner and student accommodation for students offering to present talks 
or posters at the conference sheduled in Leiden on 11-14 August. Eligibility is restricted 
to individuals who are currently registered for a PhD. Applications will close at <strong>17:00 on Friday 27 March</strong>. 
Decisions will be taken by a joint assessment panel, with results expected to be 
announced by Friday 17 April 2009.</p>

<iframe height="1500" allowTransparency="true" frameborder="0" scrolling="no" 
style="width:100%;border:none" src="http://systass.wufoo.com/embed/p7x0k1/">
<a href="http://systass.wufoo.com/forms/p7x0k1/" title="Systematics Association 
Biennial 2009 Bursaries">Fill out my Wufoo form!</a></iframe> <small>
<a href="http://wufoo.com/">Powered by Wufoo</a></small>
