<p><strong>CoSyst Round 3 Panel Membership:</strong></p>

<ul>
<li>Dr Julie Hawkins (Chair): Centre for Plant Diversity and Systematics, School of Biological Sciences, University of Reading.</li> 
<li>Dr Liam Dolan: Cell and Developmental Biology Department, John Innes Centre.</li>
<li>Dr Sandy Knapp: Department of Botany, Natural History Museum.</li>
<li>Dr Tim Littlewood: Department of Zoology, Natural History Museum. </li>
<li>Dr Seb Shimeld: Evolution and Development research group, Department of Zoology, University of Oxford.</li>
<li>Dr Mark van der Giezen: Centre for Eukaryotic Evolutionary Microbiology, School of Biosciences, University of Exeter.</li>
<li>Dr Tom Richards (Observer): Centre for Eukaryotic Evolutionary Microbiology, School of Biosciences, University of Exeter. Tom is observing the panel for the third round of CoSyst in his capacity as Systematics Research Fund chair for the Linnean Society and Systematics Association.</li> 
</ul>
