        <hr>
        <p class="title">
          SRF
        </p>
        <p>A joint fund of the Linnean Society and the Systematics Association, 
				the Systematics Research Fund (SRF) provides grants annually for small-scale 
				research projects in the field of systematics.
				<span style="background-color: #cc6633;">Applications for the 2016/17
				SRF are now open</span><br>
				<a href="/awards/srf.shtml">Find out more.</a>
				</p>
