        <hr>
        <p class="title">
          SRF
        </p>
        <p>A joint fund of the Linnean Society and the Systematics Association, 
				the Systematics Research Fund (SRF) provides grants annually for small-scale 
				research projects in the field of systematics.  Applications for the 2015/16 
				SRF are now closed<br>
				<a href="/awards/srf.shtml">Find out more.</a>
				</p>
