
<iframe height="2200" frameborder="0" scrolling="yes"
style="width:80%;border:none"
src="http://systass.wufoo.com/embed/systematics-research-fund/"
id="systass-systematics-research-fund"
name="systass-systematics-research-fund">
<a href="http://systass.wufoo.com/forms/systematics-research-fund/">
Fill out my Wufoo form!</a>
</iframe>

<P style="color: #ff3333; font-weight: bold;">Note: all applicants will receive an automatic email response following successful electronic submission</P>
