<p class="title">SRF 2009/2010 - Online Application Form</P>

<p>Questions about the application procedure can be sent to  

 <script type="text/javascript">
 <!--
  var usr = "t.a.richards";
  var dom = "systass";
  var tld = "org";
  var ady = usr + "@" + dom + "." + tld;
  document.write("(<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>)")
//-->
</script>

</p>

<!-- add link to include for wufoo form -->
<iframe allowTransparency="true" height="2000" frameborder="0" 
scrolling="no" style="width:100%;border:none" 
src="http://systass.wufoo.com/embed/z7p8a3/">
<a href="http://systass.wufoo.com/forms/z7p8a3/" title="Systematics Research Fund  2009">
Fill out my Wufoo form!</a>
</iframe>
