<p class="title">SRF 2007/2008 - Online Application Form</P>

<p>Questions about the application procedure can be sent to  

 <script type="text/javascript">
 <!--
  var usr = "systresfund2007";
  var dom = "googlemail";
  var tld = "com";
  var ady = usr + "@" + dom + "." + tld;
  document.write("(<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>)")
//-->
</script>

</p>

<!-- add link to include for wufoo form -->
<iframe height="1339" allowTransparency="true" frameborder="0" scrolling="no" style="width:100%;border:none;background-color: #ffffcc;" 
src="http://systass.wufoo.com/embed/systematics-research-fund-2007/" title="HTML Form">
<a href="http://systass.wufoo.com/forms/systematics-research-fund-2007/" title="HTML form">Fill out my Wufoo form!</a></iframe>

<small><a href="http://wufoo.com/">Powered by Wufoo</a></small>
