<p class="title">SRF 2008/2009 - Online Application Form</P>

<p>Questions about the application procedure can be sent to  

 <script type="text/javascript">
 <!--
  var usr = "t.a.richards";
  var dom = "systass";
  var tld = "org";
  var ady = usr + "@" + dom + "." + tld;
  document.write("(<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>)")
//-->
</script>

</p>

<!-- add link to include for wufoo form -->
<iframe height="1253" allowTransparency="true" frameborder="0" 
scrolling="no" style="width:100%;border:none" 
src="http://systass.wufoo.com/embed/s7x1x7/">
<a href="http://systass.wufoo.com/forms/s7x1x7/" title="Systematics Research Fund  2008">
Fill out my Wufoo form!</a>
</iframe>
