<p>The closing date for applications to the 2011/12 round was <strong>31st January 2012</strong> and 
the following projects have been funded.</p>

<p class="title">2011/12</p>

<ol>
<li><strong>Okamura and Bass (Natural History Museum, London)</strong><br>
<strong>Unexplored parasite diversity and fisheries disease risk</strong><br>
The main systematic component of this project is to investigate unexplored diversity 
of two understudied parasitic groups that cause important diseases in freshwater 
and marine fisheries - the <em>Myxozoa</em> and <em>Ascetosporea</em>. Novel small subunit ribosomal 
RNA genes of these groups detected in environmental gene libraries will improve 
understanding of their taxonomy and systematics through new, more comprehensive 
and highly resolved phylogenies. The project will also entail descriptions of new 
taxa with information on host identity and potential lifecycle via an integrated 
approach (molecular techniques, microscopy, host response, pathology) in collaboration 
with the Centre for Environment, Fisheries &amp; Aquaculture Science (Cefas).</li>

<li><strong>Boxshall and Huys (Natural History Museum, London)</strong><br>
<strong>Essential sequencing and systematics for sealice</strong><br>
Sealice (ectoparasitic copepods of the family <em>Caligidae</em>) are a major problem in 
commercial aquaculture, but our understanding of their host relationships and developmental 
patterns is hampered by uncertainty over the validity of genera, relationships between 
genera, and the boundaries of the family. This project will generate a systematic 
and taxonomic framework for caligids based on a molecular phylogenetic backbone. 
It will help stabilise their classification and provide a foundation for an improved 
understanding of sealice biology. Sequence data generated will be published on-line 
boosting available sequences on sealice, enhancing comprehensive taxonomic analysis, 
and allowing rapid diagnosis of important pest species.</li>


<li><strong>Rossiter (Queen Mary University of London) and Bates (Harrison Zoological Museum)</strong><br>
<strong>The diversification of horseshoe bats: sorting the trees from the phylogenetic forest</strong><br>
Rapid gains in throughput and cost-effectiveness of Next Generation Sequencing mean 
that phylogenomic approaches will become increasingly important in taxonomy and 
systematics. Yet as the volume of available sequence data rises, so will the frequency 
of phylogenetic discordance between genes. Resolving species relationships using NGS 
data will necessitate correcting for this problematic phenomenon, demanding appreciation 
of the nature, causes and consequences of discordance in a range of evolutionary contexts. 
To achieve this and also distinguish between conflicts caused by noise versus real 
evolutionary processes, we will develop a method for rapid gene-by-gene screening 
and classification of discordance at a genome-scale.</li>


<li><strong>Day (Natural History Museum, London) and Gharbi (The University of Edinburgh, The GenePool)</strong><br>
<strong>Untangling the systematics of soda lake cichlids using a genomic approach</strong><br>
Cichlid fishes are model organisms in speciation research. It is therefore surprising 
that African soda lake cichlids, inhabiting one of the most hostile environments 
on Earth supporting fish life have been overlooked. To elucidate mechanisms promoting 
and maintaining diversification in such extreme conditions, the systematics of this 
young, ecomorpholgically variable species-flock need to be resolved. This is only 
now possible with the advent of new sequencing technology and phylogenetic methods. 
Here, we propose to generate SNP data using the genotyping-by-sequencing approach 
of RAD-tags, applying a Bayesian modelling approach, to untangle the diversity and 
systematics of this unique adaptive radiation.</li>


<li><strong>Jungblut (Natural History Museum, London) and Edwards (Aberystwyth University)</strong><br>
<strong>Taxonomic evaluation of cryoconite cyanobacteria: barcoding keystone taxa on glaciers</strong><br>
The project will provide the first comprehensive taxonomic assessment of the cyanobacteria 
of meltwater habitats on Arctic, Antarctic and alpine glaciers. It will provide 
cultured isolates for whole genome phylogenetics that will improve resolution of 
evolutionary relationships of glacier-dwelling cyanobacteria and their position 
within the phylum Cyanobacteria. The results will assist determining the importance 
of glacial systems for microbial taxonomic diversity in permanently cold environments. 
The impacts of climate change are amplified in the cryosphere, particularly the 
Polar Regions, so the taxonomic results will provide baseline data essential to 
studying the effects of climatic change on biodiversity in glacial ecosystems.</li>


<li><strong>Glover (Natural History Museum, London)</strong><br>
<strong>Systematics of Antarctic scaleworms: adaptive radiation in an extreme environment</strong><br>
Systematics and taxonomy completely underpins our project; without a comprehensive 
systematics of this group it would be completely impossible to test these important 
globally-relevant hypotheses with regard how marine taxa have responded to a warming 
Antarctic – both over recent geological time (the last 15 Ka) and in recent ecological 
time as a result of anthropogenic influences. Our project, publications and follow-on 
grant, will also highlight the importance of systematics and we will utilise the 
outreach potential of the NHM in delivering these messages to key stakeholders, 
including both the general public, research councils and government.</li>



<li><strong>Hall (University of Liverpool) and Jackson (Wellcome Trust Sanger Institute)</strong><br>
<strong>Inside the Trojan horse: systematics of <em>Acanthamoeba</em> spp. and their endosymbionts</strong><br>
<em>Acanthamoeba</em> spp. are free-living, unicellular eukaryotes that have a natural ability 
to sustain a diverse microflora of primary and secondary bacterial endosymbionts, 
which can include potent Human pathogens. There is a clear need for robust systematics 
of both Acanthamoeba spp. and their endosymbionts, which is currently lacking. We 
believe that the known microbial interactions among <em>Acanthamoeba</em> spp. are a fraction 
of the reality. Our vision is to systematically survey Human and natural environments 
to reveal the scale and diversity of these associations, creating an engine for 
the discovery of novel microorganisms and so substantially increase our knowledge 
of microbial taxonomy.</li> 


<li><strong>Hudson and Gharbi (University of Edinburgh)</strong><br>
<strong>Testing RAD sequences for phylogenetics in the young genus <em>Antirrhinum</em></strong><br>
Relationships between young or rapidly radiated taxa are often obscured by lineage 
sorting and hybridisation. Comparing multiple nuclear loci offers a potential solution, 
but requires amplifying many genes individually or whole-genome sequencing.  Here 
we will test a cost-effective alternative – restriction-site associated DNA (RAD) 
sequencing – developed recently for intraspecific studies.  Applying it to the young 
Mediterranean genus <em>Antir</em>rhinum (snapdragons), we will (a) test RAD in different 
methods of phylogenetic reconstruction, (b) possibly resolve a robust phylogeny 
for Antirrhinum and (c) examine whether adaptive loci have a different evolutionary 
history to the bulk of the nuclear genome. </li> 


<li><strong>Brodie (Natural History Museum, London) and Yallop (University of Bristol)</strong><br>
<strong>A taxonomic discovery system for macroalgal microbiomes</strong><br>
This project proposes to develop a microbial diversity assessment system for marine 
macroalgae and is therefore dependent on a robust taxonomy in order to be able to 
discover and describe the microbiomes of the chosen species, the red calcifying 
red alga <em>Corallina officinalis</em>, and from which spatial and temporal comparisons 
can be made.  It will also enable the exploration of microbiome cryptic diversity 
and will enable more complete phylogenies to be made of less-well known taxonomic 
groups and in doing so contribute to improving our understanding of evolutionary 
relationships of these organisms. </li>


<li><strong>Vorontsova and Forest (Royal Botanic Gardens, Kew)</strong><br>
<strong>Reconstructing Madagascar grassland history using the three-awn grasses</strong><br>
Madagascar grassland species richness and endemism are currently impossible to assess 
due to lack of species knowledge. Species delimitation of <em>Aristida</em> and <em>Sartidia</em> 
in Madagascar will be carried out using traditional micromorphological methods measuring 
spikelet parts from selected herbarium specimens. Delimitation of endemic species 
will provide a platform for DNA based lineage history reconstruction. The taxonomic 
revision of <em>Aristida</em> and <em>Sartidia</em> in Madagascar, distribution maps, and identification 
keys will provide a baseline information source on Madagascar Aristidoideae. This 
project will form the first part of PI's work towards the <em>Grass Flora of Madagascar</em>.</li>


<li><strong>Pressel (Natural History Museum, London) and Duckett (Queen Mary University of London)</strong>
<strong>Scratching the surface: a morphological framework to understanding cuticle origin and evolution</strong><br>
We have the long-term goal of searching for novel morphological characters to resolve 
early land plant phylogeny. Our proposal for detailed characterization of the cuticle 
throughout life cycles will provide much needed ontogenetic and ultra-structural 
data to support or challenge molecular phylogenies. We will also generate new morphological 
and biochemical characters to evaluate links between early land plants and algal 
lineages, and for the interpretation of paleobotanical cuticle deposits. Finally 
systematic descriptions of the cuticle will yield insights into the early function 
of the cuticle in desiccation biology, and the origin of this most important land 
plant innovation.</li>


</ol>
