<p><strong>SynTax Panel Membership:</strong></p>

<ul>
<li><strong>Dr Tom Richards, University of Exeter (Chair)</strong></li>
<li>Dr Bill Baker, Royal Botanic Gardens Kew</li>
<li>Professor Mark Blaxter, University of Edinburgh</li>
<li>Professor Neil Hall, University of Liverpool</li>
<li>Dr Julie Hawkins, University of Reading</li>
<li>Dr Sandy Knapp, The Natural History Museum</li>
<li>Dr Max Telford, University College London</li>
</ul>
