<p>The closing date for applications to the 2009/10 round was <strong>31st January 2010</strong> and 
the following projects have been funded.</p>

<p class="title">2009/10</p>

<ol>
<li><strong>Dr van Veen (University of Exeter)</strong>
<br><strong>Resolving Alloxystini taxonomy to facilitate the geographic comparison 
of insect food webs</strong>
<br>This project has a strong taxonomic focus within an ecological context. It will 
catalogue all currently known species of <em>Alloxystini</em> wasps, including the many currently 
undescribed and unnamed ones. It will produce an easily accessible identification 
resource based on an extensive image library and a database of morphological measurements. 
This will build on the phylogenetic structure of an aphid-based food web, which 
includes the construction of a molecular phylogeny of the <em>Alloxystini</em>.</li>

<li><strong>Dr Nichols (Queen Mary University of London) and Dr Garner (Institute 
of Zoology, London)</strong>
<br><strong>Laying the taxonomic foundations for the study of UK ranaviruses</strong> 
(DEFRA funded)
<br>British amphibian populations are experiencing a wave of infection 
by ranaviruses.  The taxonomic status of these viruses is unclear, consequently 
their origins have not been determined - hence it is difficult to devise control 
strategies. Furthermore, there appear to be biological differences between viruses 
infecting different species of amphibian, but without a sound understanding of the 
viral taxonomy and origins it has proved difficult to establish which species are 
infecting which other. The viruses are a serious threat to UK BAP priority species.</li>

<li><strong>Dr Glover (Natural History Museum, London) and Dr Dahlgren (G&ouml;teborg 
University, G&ouml;teborg)</strong>
<br><strong>Dispersal in the deep: molecular systematics and population connectivity 
of deep-sea annelids</strong>
<br>This project will undertake taxonomic descriptions and molecular systematic analysis 
on at least 10 new species of poorly-studied, but potentially species-rich deep-sea 
annelids. The generic clades that these species belong to have global distributions, 
but the patterns at the species level and the degree of genetic structuring with 
distance are unknown. The results will have important consequences for our understanding 
of dispersal in the oceans, population connectivity, and the drivers of biodiversity 
in the deep sea.</li>

<li><strong>Dr McDonald (Bangor University) and Dr Flint (University of Aberdeen/
The Rowett Institute of Nutrition and Health)</strong>
<br><strong>Determination of the phenotypic taxonomy of the bacterial phylum 
Fibrobacteres</strong>
<br>This project will provide the first assessment of the diversity, global distribution, 
phenotype, phylogeny and taxonomy of novel lineages belonging to the poorly studied 
bacterial phylum, Fibrobacteres, using a combined molecular/genomic and cultivation-based 
approach. Significant outputs would include a completely revised taxonomy of the 
Fibrobacteres phylum and the environmental distribution of its component taxa, and 
for the first time, a collection of cultivated strains with phenotypic profiles. 
These taxonomic data will make a much-needed contribution to the characterisation 
of a potentially novel cellulase system, and the provision of evidence for a role 
of fibrobacters in global carbon cycling.</li>

<li><strong>Dr Richards (University of Exeter) and Dr Bass (Natural History Museum, 
London)</strong>
<br><strong>Global evolutionary complexity of freshwater alveolates: a new threat 
to frogs?</strong> (DEFRA funded).
<br>This project uses environmental DNA, phylogenetics, microbial culture isolation, 
and microscopy to identify the evolutionary complexity, biogeography, and comparative 
taxonomy of a novel group of parasitic alveolate protists that appear to infect 
tadpoles. The project aims include a formal taxonomic description of these novel 
protists and an assessment of their distribution within UK environments.</li>

<li><strong>Dr Perotti (University of Reading) and Dr Desch (University of Connecticut)</strong>
<br><strong>Follicular mites of primates: taxonomy and molecular markers for 
further co-evolutionary studies.</strong>
<br>This project focuses on the description, for the first time, of the follicular mite 
species (<em>Acari</em>, <em>Demodecidae</em>) of great and lesser apes.  Few mite species from New 
World monkeys and lemurs are known so far. The project includes a systematic approach 
by producing molecular markers of the mites and will also include phylogenetic and 
co-phylogenetic studies of the mites and their primate hosts.</li>

<li><strong>Dr Olson (Natural History Museum, London) and Dr Berriman (Wellcome 
Trust Sanger Institute, Cambridge).</strong>
<br><strong>Toward phylogenetic resolution of parasitic flatworms through comparative 
analysis of complete genomes</strong>
<br>This project proposes a novel application of whole-genome data to resolve a critical 
question in the evolution and systematics of parasitic flatworms (Platyhelminthes). 
It will serve as an example for how large-scale genomic data can be used in Systematics, 
and makes phylogenetically informative characters publicly available for a wider 
range of taxa within the phylum.</li>

<li><strong>Dr Hofreiter and Dr Missa (University of York).</strong>
<br><strong>Systematics of <em>Oribius</em> weevils (Coleoptera, Curculionidae) in New 
Guinea</strong>
<br>This project proposes to work on the systematics and biogeography of <em>Oribius</em> weevils, 
a genus endemic to the island of New Guinea. Fifty-eight species are currently recognised, 
including a number of very serious pests to agriculture, which threaten the food 
security of this developing nation. Despite its economic importance, the genus has 
not received any taxonomic attention for over 50 years. The intended project will 
therefore be of immediate practical value for pest identification and management. 
It will also allow us to reconstruct the evolutionary history of this diverse genus 
and elucidate the exact role that geology played in its diversification.</li>

<li><strong>Dr Vogel (The Natural History Museum, London) and Dr Hollingsworth 
(Royal Botanic Garden, Edinburgh).</strong>
<br><strong>The War of Bluebells</strong>
<br>This project focuses on <em>Hyacinthoides</em> which comprises 11 species, including the 
British bluebell (<em>H. non-scripta</em>). The genus shows examples of recent origins of 
localised endemic species, and also evidence for narrow stable hybrid zones between 
<em>H. hispanica</em> and <em>H. non-scripta</em> in Iberia where both species are native, and extensive 
introgression in the UK where <em>H. non-scripta</em> is native but <em>H. hispanica</em> is introduced. 
Understanding species limits and the dynamics of hybridisation and diversification 
will shed light into the mechanisms underpinning recent speciation/maintaining species 
boundaries, and will also provide information to assess the threat level to the 
native British bluebell from hybridisation by <em>H. hispanica</em>.</li>

<li><strong>Dr Helgason (University of York)</strong>
<br><strong>Taxonomic diversity and biogeography of the arbuscular mycorrhizas</strong>
<br>SSU rRNA gene analysis of environmental samples suggests much higher diversity of 
Glomeromycotan fungi in nature than can currently be cultured. This project will 
yield an understanding of the taxonomic diversity present in the unculturable species 
in the Phylum. In addition, it is becoming clear that phylogeny of other genes does 
not support the SSU rRNA phylogeny of this phylum. This proposal will develop an 
actin gene marker for use in field systems that will more accurately reflect both 
the identity and phylogenetic relationships within the unculturable component of 
this important group of fungi.</li>

<li><strong>Dr Williams (Natural History Museum, London) and Dr Goulson (University 
of Stirling)</strong>
<br><strong>Resolving cryptic bumblebees of the lucorum-group</strong>
<br>Bumblebee species closely related to <em>Bombus lucorum</em> dominate north temperate pollinator 
assemblages and are also key commercial pollinators, making their accurate identification 
important for pure and applied biology. However, traditional species identification 
based on colour patterns is impossible for many individuals and is often wrong according 
to recent genetic data. Pilot work suggests that global sampling and genetic analysis 
may produce new, morphologically diagnosable groups. This project will combine this 
broad global approach with a local in-depth study to clarify the taxonomy, distribution, 
ecology, and conservation status of this important group world-wide and in the UK.</li>

<li><strong>Dr Glover (University of Cambridge) and Dr Rudall (Royal Botanic Gardens, 
Kew)</strong>
<br><strong>Molecular control of petal spot evolution in Cape Flora daisies</strong>
<br>This project combines plant systematics and development to study the molecular drivers 
of petal spot evolution within a species complex. Geographically distinct populations 
of the South African daisy <em>Gorteria</em> have distinct petal spot phenotypes, allowing us 
to investigate the molecular changes that underlie the morphological evolution between 
populations of a single species. Determining the direction of petal spot evolution 
within the context of a detailed phylogenetic analysis and identifying the genes 
encoding the regulators of petal spot morphology will provide a complete picture 
of the molecular evolution of a key trait  central to morphological differentiation 
and speciation.</li>
</ol>