<p>The closing date for applications to the 2010/11 round was <strong>31st January 2011</strong> and 
the following projects have been funded.</p>

<p class="title">2010/11</p>

<ol>
<li><strong>Collins (University of York) and Barnes (Royal Holloway, University of London)</strong><br>
<strong>Collagen: the barcode of death</strong>
<br>By developing a tool for routine identification of samples, and providing a 
means to infer the evolutionary relationships of novel palaeontological specimens, 
the project is inherently taxonomic and systematic. The proposed case studies deal 
with evolutionary histories of three poorly resolved groups of taxa, and will substantially 
enhance our understanding of evolution, adaptation, radiation and convergence, whilst 
also improving collections management for Quaternary fossil material.</li>

<li><strong>Purvis (Imperial College London) and Darling (University of Edinburgh)</strong><br>
<strong>Species limits in planktonic foraminifera</strong>
<br>Planktonic foraminifera have probably the best fossil record of any group, making 
them a model system for macroevolutionary research.  However, genetic evidence indicates 
that many of the extant species recognised from morphology contain deep divergences, 
at least some of which probably delimit good genetic species.  We propose two linked 
investigations. (1) We will apply a recently-developed analytical approach to demarcate 
the genetic species statistically; this will also estimate their ages.  (2) We will 
use non-destructive computer tomography (CT) scans of sequenced specimens on four 
morphospecies, with the aim of identifying morphological criteria for diagnosing 
the genetic species.</li>  

<li><strong>Bass (Natural History Museum) and Neuhauser (University of Innsbruck)</strong><br>
<strong>Phytomyxids: A hidden world of parasites and symbionts</strong>
<br>Phytomyxid protists are very poorly known rhizarian parasites/symbionts of plants, 
algae, and oomycetes. Recent molecular environmental studies suggest that they are 
much more diverse, and have a wider range of host species, than previously known. 
These studies have also begun to reveal related but highly distinct lineages about 
which nothing else is known. This project will sample phytomyxids and their relatives 
from environmental samples in a much more targeted way than previously attempted, 
and will use ecological, phylogenetic, and morphological (microscopy and culture-based) 
techniques to strongly advance knowledge of this group and their position on the 
eukaryote tree of life.</li>

<li><strong>Purnell (University of Leicester)</strong><br>
<strong>Taphonomic bias in taxonomic and systematic analysis of fossils</strong>
<br>Recent work has reaffirmed the importance of fossils, especially those representing 
non-biomineralised animals, in systematic and evolutionary biology (see Background 
and Rationale). This research will have a direct bearing on the taxonomy and phylogenetic 
systematic analysis of non-biomineralised fossils, particularly phyllocarids and 
potential stem malacostracans (crustaceans). It will allow us to understand how 
taphonomic processes of decay and preservation distort and bias the taxonomic and 
systematic information content of exceptionally-well-preserved fossils. Without 
this understanding such fossils cannot realise their true potential.</li> 

<li><strong>Falcon-Lang (Royal Holloway University of London)</strong><br>
<strong>Early angiosperm diversity and ecology: seeing the trees from the wood</strong>
<br>This project addresses Charles Darwin's "abominable mystery": the origin, evolution 
and ecology of the earliest angiosperms. Specifically, it focuses on fossil wood, 
which has received little attention in earlier studies of angiosperm evolution. Using 
morphometrics and multivariate character analysis, I plan to identify Cretaceous 
(140-65 million year old) fossil wood assemblages with greater taxonomic precision 
than previously possible to improve knowledge of angiosperm diversity during a crucial 
evolutionary phase. This 'proof of concept' study will be used as a springboard 
for a NERC Standard Grant application.</li>

<li><strong>Wills (University of Bath) and Wilkinson (The Natural History Museum)</strong><br>
<strong>Building the arthropod supertree interactively: Malacostracan crustaceans as a test case</strong>
<br>We will produce MRP and other supertrees of malacostracan species, synthesising 
200+ primary trees from the literature. Rather than generate this as a one-off, 
all of the data and trees will be made available online. This will be searchable 
using numerous tags (e.g., source data type, publication year, authors, tree and 
node support metrics) and linked to embedded software enabling inexperienced users 
to generate error-free supertrees to any specifications. In addition, the project 
will embed taxonomic knowledge, ensuring standard and repeatable best practice. 
This will constitute a proof of principle pilot for a proposed interactive supertree 
database of all arthropods.</li>

<li><strong>Sands and Griffiths (British Antarctic Survey)</strong><br>
<strong>Systematics and taxonomy of Antarctic ophiuorids: a next-gen holistic approach</strong>
<br>We propose to refine and demonstrate the application of genomics using next 
generation sequencing technology to facilitate morphology based systematics and 
taxonomy of individual specimens.  We will address a complex taxonomic issue present 
in Antarctic ophiuroids involving potential generic synonyms and species complexes 
by sequencing thousands of gene regions for each individual, determining allelic 
variation of each gene, and co-analysing both phylogeny and multi-locus genotype 
clustering using a user-friendly bioinformatic pipeline.  The holistic approach 
we propose will radically alter and reduce to laboratory time and costs of molecular 
evolutionary studies, while  greatly increasing the amount of data and its applicability.</li>

<li><strong>W&uuml;ster and Mulley (School of Biological Sciences, Bangor University)</strong><br>
<strong>Cryptic reptile diversity in a floristic biodiversity hotspot</strong>
<br>Effective conservation of biodiversity hotspots requires information on the 
diversity of all major groups of organisms. The southern African Cape Floristic 
Region (CFR) has been recognised primarily for its floral diversity, but early data 
suggest that it may be of hitherto underestimated importance for faunal diversity. 
We seek to develop and use microsatellite markers to investigate and redefine species 
limits in four species of CFR reptile showing strong phylogeographic structure, 
with the aim of uncovering cryptic species, and as a prelude to wider-ranging studies 
on the patterns and processes of reptile speciation in the CFR.</li>    

<li><strong>Wilkinson (The Natural History Museum) and Day (University College London)</strong><br>
<strong>History and Future of the Seychelles Herpetofauna</strong>
<br>The research is on diversity and its causes at a number of temporal scales and 
is thus broadly systematic. Seychellean caecilians are monophyletic with currently 
six species in three genera.  Previous taxonomic treatments, the most recent more 
than 50 years ago, have disagreed on genera and on whether island populations of 
the six currently recognised species, which show some morphological differences, 
represent distinct taxa. We will test species and generic concepts using molecules 
and morphology and provide a comprehensive taxonomic review of the group. Revisionary 
taxonomy will also underpin the planned comparative broadening of this study to 
other taxa.</li>

<li><strong>Pennington (Royal Botanic Garden Edinburgh) and Coley (Department of Biology, University of Utah)</strong><br>
<strong>Chemistry, taxonomy and diversification in tropical plants: a case study of <em>Inga</em></strong>
<br><em>Inga</em> is one of the most important tree genera in the rain forests of Latin America. 
It is species-rich, abundant, and economically important because of its edible fruits 
and rapid growth, which make it widely used as a multipurpose tree in agroforestry 
(e.g., as coffee shade). This proposal will deliver bespoke DNA markers for <em>Inga</em> 
that can improve species delimitation, provide a resolved species phylogeny, and 
investigate intraspecific genetic variation. An improved taxonomy and phylogeny 
will underpin future applied research on <em>Inga</em> species and be a springboard to understanding 
the processes that have led to its high diversity.</li>

<li><strong>Dentinger (Royal Botanic Gardens, Kew) and McLaughlin (University of Minnesota)</strong><br>
<strong>Molecular systematics of the enigmatic attine-ant mutualistic coral mushroom family Pterulaceae</strong>
<br>The attine ant-fungus mutualism is a classic coevolutionary system. Recent evidence 
suggests one small group of attines in the genus <em>Apterostigma</em> switched fungal cultivars 
twenty million years ago from gilled to coral mushrooms (Pterulaceae), a remarkable 
event that remains unexplained. This project will improve our systematic knowledge 
of the Pterulaceae by identifying phylogenetically informative loci and improving 
taxon sampling. The results will provide the foundation for a contemporary systematic 
revision of a poorly known group of fungi, allowing for the formal taxonomic classification 
of the unusual coral mushroom ant cultivars for the first time.</li>

<li><strong>Scotland (University of Oxford) and Carine (Natural History Museum, Dept of Botany)</strong><br>
<strong>Foundation Monographs - accelerating the pace of taxonomy</strong>
<br>This research project is fundamentally taxonomic in scope and content.</li>

<li><strong>Leitch (Queen Mary University of London) and Leitch (Jodrell Laboratory)</strong><br>
<strong>Status of homoploid hybrids in a model genus for sympatric speciation</strong>
<br>Interspecific hybridization events differ in their propensity to produce new 
hybrid species, both at the allopolyploid and homoploid level. Factors affecting 
these propensities are poorly understood, partly due to a lack of alpha-taxonomy 
on homoploid hybrids. The plant genus <em>Tragopogon</em> L. (Asteraceae) includes classic 
models species for the study of allopolyploid speciation in the USA. The genus also 
contains many European homoploid hybrids. These hybrids have not been investigated 
despite the valuable insight it will give to our understanding of related allopolyploid 
species. We will characterize their parentage and stability and to determine whether 
incipient speciation is occurring.</li> 

<li><strong>Shaw (Centre for research in Ecology) and Emerson (Biological Sciences, 
University of East Anglia)</strong><br>
<strong>A molecular taxonomic approach to resolving species boundaries within British 
members of the genera <em>Lepidocyrtus</em> and <em>Entomobrya</em> (Arthropoda: Pancrustacea: Collembola).</strong>
<br>We intend to use mitochondrial and nuclear DNA to validate species boundaries 
in two widespread genera of UK Collembola; <em>Lepidocyrtus</em> and <em>Entomobrya</em>.  Existing 
taxonomy in both is colour-based and suspect.  Recent work around the Mediterranean 
basin has shown the same morphospecies of <em>Lepidocyrtus</em> that occur in the UK to contain 
multiple unrelated clades.  It is unclear whether most UK records of <em>Entomobrya</em> 
nivalis are valid or mixed with <em>E. intermedia</em>.  We will collect these surface-active 
Collembola from multiple habitats either side of the Devensian borderline, seeking 
to establish the genetic validity of species boundaries as currently defined.</li>  
</ol>
