        <p>
          Details of the scheme, which will provide funding of
          &pound;5k to &pound;30k for projects with a substantial
          systematic/phylogenetic/taxonomic component are
          <a href="SyntaxGuidelines-FAQs_2011_12.pdf" rel=
          "external">here</a>. The scheme is available only to
          UK-based applicants.
        </p>
        <p class="title">
          Guidelines
        </p>
        <p>
          <a href="SyntaxGuidelines-FAQs_2011_12.pdf" rel=
          "external">Guidelines for applying for SynTax
          funding</a><br>
          A FREE copy of the Adobe<sup>&copy;</sup> Acrobat
          Reader is available from <a href=
          "http://www.adobe.com/products/acrobat/readstep2.html"
          rel="external">here.</a>
        </p>
