<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="J7ELZLLE68Q74">
<table style="text-align: center;">
<tr><td>
				<img src="../images/SystAssLogo-75small.png" width="127"
        height="160" alt="Systematics Association" title=
        "Systematics Association">
				</td></tr>
<tr><td><input type="hidden" name="on0" value="Select number of tickets">Select number of tickets</td></tr><tr><td><select name="os0">
	<option value="1 Ticket">1 Ticket &pound;30.00 GBP</option>
	<option value="2 Tickets">2 Tickets &pound;60.00 GBP</option>
	<option value="3 Tickets">3 Tickets &pound;90.00 GBP</option>
	<option value="4 Tickets">4 Tickets &pound;120.00 GBP</option>
	<option value="5 Tickets">5 Tickets &pound;150.00 GBP</option>
	<option value="6 Tickets">6 Tickets &pound;180.99 GBP</option>
</select> </td></tr>
<tr><td><input type="hidden" name="on1" value="Your Name">Your Name</td></tr><tr><td><input type="text" name="os1" maxlength="200"></td></tr>
<tr><td><input type="hidden" name="on2" value="Booking Reference">Booking Reference</td></tr><tr><td><input type="text" name="os2" maxlength="200"></td></tr>
</table>
<input type="hidden" name="currency_code" value="GBP">
<input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online.">
<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>
