<!-- http://cookiesdirective.com/ -->
<script type="text/javascript">
    function cookiesDirectiveScriptWrapper(){
        // Cookie creating scripts etc here.... 
     cdScriptAppend('google-analytics.js', 'head'); 
    }
</script>
<script type="text/javascript" src="http://www.systass.org/1.5.js">
</script>
<script type="text/javascript">
    // The position of the disclosure ('top' or 'bottom')
    // Number of times to display disclosure. Enter 0 to show it forever!!!!
    // The URI of your privacy policy
    // A comma separated list of scripts which will create cookies
    cookiesDirective('top',0,'privacy.shtml','Google Analytics');
</script>