<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title></title>
  </head>
  <body>
    <iframe width="180" height="250" frameborder="0" scrolling=
    "no" marginheight="0" marginwidth="0" src=
    "https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=The+Linnean+Society+of+London,+Burlington+House,+Piccadilly,+London+W1J+0BF&amp;aq=&amp;sll=51.497149,-0.176382&amp;sspn=0.043121,0.077162&amp;ie=UTF8&amp;hq=The+Linnean+Society+of+London,+Burlington+House,+Piccadilly,+London+W1J+0BF&amp;t=m&amp;ll=51.508905,-0.139336&amp;spn=0.013889,0.032015&amp;output=embed">
    </iframe><br>
    <small><a href=
    "http://goo.gl/maps/67P5b"
    style="color:#0000FF;text-align:left">View Larger
    Map</a></small>
  </body>
</html>
