<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title></title>
  </head>
  <body>
    <iframe width="180" height="250" frameborder="0" scrolling=
    "no" marginheight="0" marginwidth="0" src=
    "https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;aq=&amp;sll=51.512171,-0.097985&amp;sspn=0.175847,0.308647&amp;ie=UTF8&amp;hq=Natural+History+Museum,+Cromwell+Road,&amp;hnear=SW7+5BD,+United+Kingdom&amp;t=m&amp;ll=51.497149,-0.176382&amp;spn=0.013359,0.017166&amp;z=14&amp;output=embed">
    </iframe><br>
    <small><a href=
    "https://maps.google.co.uk/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Natural+History+Museum,+Cromwell+Road,+London++SW7+5BD&amp;aq=&amp;sll=51.512171,-0.097985&amp;sspn=0.175847,0.308647&amp;ie=UTF8&amp;hq=Natural+History+Museum,+Cromwell+Road,&amp;hnear=SW7+5BD,+United+Kingdom&amp;t=m&amp;ll=51.497149,-0.176382&amp;spn=0.013359,0.017166&amp;z=14"
    style="color:#0000FF;text-align:left">View Larger
    Map</a></small>
  </body>
</html>
