<div id="leftCol">
<!-- Add HTML for Left Column ?menu?links? -->
<div id="links">
<a href="/" accesskey="h" title="the home page of the site">Home<span> Return to the home page of the site</span></a>
<a href="/about/" title="Learn more about the Systematics Association">About<span> Learn more about the Systematics Association</span></a>
<a href="/membership/" accesskey="m" title="details about membership of the association">Membership<span> For further details about membership of the association</span></a>
<a href="/newsletter/" accesskey="n" title="Download copies of the newsletter">Newsletters<span> Download copies of the newsletter</span></a>
<a href="/publications/" accesskey="p" title="Details of Systematics Association publications">Publications<span> Details of SA publications</span></a>
<a href="/awards/" accesskey="a" title="Details of research grants &amp; awards">Awards<span> Details of research grants &amp; awards</span></a>
<a href="/events/" accesskey="e" title="Details of forthcoming events &amp; meetings">Events<span> Details of forthcoming events &amp; meetings</span></a>
<a href="/ysf/" accesskey="y" title="Details of the Young Systematists' Forum">YSF<span> Young Systematists' Forum</span></a>
<a href="/celebrate75/" accesskey="c" title="Celebrating 75 years of the Systematics Associaton">Celebrate75<span> 75 years of the Systematics Association</span></a>
<a href="/links/" accesskey="l" title="Links to other sites of interest">Links<span> Links to other sites of interest</span></a>
<a href="/media/" title="Podcasts and videos">Multimedia<span> Podcasts and videos</span></a>
<!-- <a href="/news/" title="Announcements and news of interest">News<span> Announcements and news of interest</span></a> -->
<!-- <a href="http://biosysteu.univie.ac.at/" rel="external" accesskey="b" title="Details of the 2nd European Biosystematics Conference">BioSyst.Eu<span> Vienna, Austria: 18-22 February 2013</span></a> -->
<a href="/biennial2015/" accesskey="b" title="Systematics - the science that underpins biology">Systematics 2015<span> 26-28 August 2015 - University of Oxford, UK</span></a>
<!-- Close id=links -->
</div>

<div id="search">
<script type="text/javascript">

// Google Internal Site Search script- By JavaScriptKit.com (http://www.javascriptkit.com)
// For this and over 400+ free scripts, visit JavaScript Kit- http://www.javascriptkit.com/
// This notice must stay intact for use

//Enter domain of site to search.
var domainroot="systass.org"

function Gsitesearch(curobj){
curobj.q.value="site:"+domainroot+" "+curobj.qfront.value
}

</script>


<form action="http://www.google.com/search" method="get" onSubmit="Gsitesearch(this)">

<p>Search SystAss.org:<br>
<input name="q" type="hidden">
<input name="qfront" type="text" style="width: 100px"><br>
<input type="submit" value="Search"></p>

</form>

<p>This free script provided by<br>
<a href="http://www.javascriptkit.com" rel="external" title="For this and over 400+ free scripts, visit JavaScript Kit">JavaScript Kit</a></p>
<!-- Close id=search -->
</div>

<!-- Close id=leftCol -->
</div>