<link rel="stylesheet" href="/stylesheets/style.css" type="text/css" media="Screen">
<link rel="stylesheet" href="/stylesheets/mobile.css" type="text/css" media="handheld">
<link rel="stylesheet" href="/stylesheets/newprint.css" type="text/css" media="print">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
<meta http-equiv="Content-Language" content="en" >
<meta name="Author" content="Rupert Wilson for Systematics Association">
<meta name="keywords" content="systematics,taxonomy,biology,botany,zoology,palaeontology,phycology,biennial,climate change,molecuar systematics,SRF,SYNTAX">
<meta name="description" content="The Systematics Association is committed to furthering all aspects of Systematic biology. It organises a vigorous programme of international conferences on key themes in Systematics, including a series of major biennial conferences to be launched in 1997. The association also supports a variety of training courses in systematics and awards grants in support of systematics research. Membership is open to amateurs and professionals with interests in any branch of biology, including microbiology and palaeontology. Members are generally entitled to attend the conferences at a reduced registration rate, to apply for grants from the Association and to receive the Associations newsletter, The Systematist and mailings of information.">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="/favicon.ico"type=" image/x-icon">
<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="http://www.systass.org/feed.xml">
<meta name="verify-v1" content="SNsWIo+RZlU6AbSFFbB/Qt6aS72s0d3kKG1mp9A3iUs=">
<script type="text/javascript" src="/incl/external.js"></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2580488-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


