<!-- PayPal USD Form -->
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="RJ6YN7RV2N9QA">
<table>
<tr><td><input type="hidden" name="on0" value="Select Membership type">Select Membership type</td></tr><tr><td><select name="os0">
	<option value="Standard Membership">Standard Membership $30.00</option>
	<option value="Student Membership">Student Membership $15.00</option>
	<option value="Retired/Unwaged Membership">Retired/Unwaged Membership $15.00</option>
	<option value="*Qualifying Countries">*Qualifying Countries $10.00</option>
</select> </td></tr>
<tr><td><input type="hidden" name="on1" value="Your name:">Your name:</td></tr><tr><td><input type="text" name="os1" maxlength="60"></td></tr>
<tr><td><input type="hidden" name="on2" value="Your e-mail:">Your e-mail:</td></tr><tr><td><input type="text" name="os2" maxlength="60"></td></tr>
</table>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_paynow_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online.">
<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>
<!-- PayPal USD Form -->
