<!-- PayPal Form -->
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="3802296">
<table>
<tr><td><input type="hidden" name="on0" value="Select Membership type">Select Membership type</td></tr><tr><td><select name="os0">
	<option value="Standard Membership">Standard Membership &pound;20.00
	<option value="Student Membership">Student Membership &pound;10.00
	<option value="Retired/Unwaged Membership">Retired/Unwaged Membership &pound;10.00
</select> </td></tr>
<tr><td><input type="hidden" name="on1" value="Your name">Your name</td></tr><tr><td><input type="text" name="os1" maxlength="60"></td></tr>
<tr><td><input type="hidden" name="on2" value="Your e-mail:">Your e-mail:</td></tr><tr><td><input type="text" name="os2" maxlength="60"></td></tr>
</table>
<input type="hidden" name="currency_code" value="GBP">
<input type="image" src="https://www.paypal.com/en_GB/i/btn/btn_paynow_LG.gif" name="submit" alt="PayPal - The safer, easier way to pay online." style="border: none;">
<img alt="" border="0" src="https://www.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>
<!-- PayPal Form -->
