<!-- PayPal Form -->
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="EQZYRZV69Z5NC">
<table>
<tr><td><input type="hidden" name="on0" value="Select Membership type">Select Membership type</td></tr><tr><td><select name="os0">
	<option value="Standard">Standard &euro;30.00 EUR</option>
	<option value="Student">Student &euro;15.00 EUR</option>
	<option value="Retired/Unwaged">Retired/Unwaged &euro;15.00 EUR</option>
	<option value="Qualifying Countries*">Qualifying Countries* &euro;15.00 EUR</option>
</select> </td></tr>
<tr><td><input type="hidden" name="on1" value="Your name:">Your name:</td></tr><tr><td><input type="text" name="os1" maxlength="200"></td></tr>
<tr><td><input type="hidden" name="on2" value="Your e-mail:">Your e-mail:</td></tr><tr><td><input type="text" name="os2" maxlength="200"></td></tr>
</table>
<input type="hidden" name="currency_code" value="EUR">
<input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online.">
<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>
<!-- PayPal Form -->