<div style="display:block;right:10px;padding-top:10px;">
<a href="https://twitter.com/#!/SystAssn" rel="external">
  <img style="padding-left:0.5em;border:0;width:160px;height:30px"
       src="/images/logo_twitter_withbird_160x30_white_blue.png"
			 title="Follow us on twitter: @SystAssn" 
			 alt="Follow us on twitter: @SystAssn" height="30" width="160"></a>
</div>
<span style="font-size:10px; float: right">Registered Charity Number 270429&nbsp;</span>