<div style="display:block;right:10px;padding-top:10px;">
<a href="http://validator.w3.org/check?uri=referer">
  <img style="padding-right:0.3em;border:0;width:88px;height:31px"
       src="/images/valid-html401.png"
			 title="Valid HTML 4.01!" 
			 alt="Valid HTML 4.01!" height="31" width="88" 
			 longdesc="http://validator.w3.org/check/referer"></a>
<a href="http://jigsaw.w3.org/css-validator/">
  <img style="padding-right:0.3em;border:0;width:88px;height:31px"
       src="/images/vcss.png"
			 title="Valid CSS!"
       alt="Valid CSS!" height="31" width="88" 
			 longdesc="http://jigsaw.w3.org/css-validator/"></a>
<a type="application/RSS+xml" href="/feed.xml" title="RSS feed"> 
  <img style="padding-right:0.3em;border:0;width:28px;height:28px"
	     src="/images/feed-icon-28x28.png"
			 title="RSS feed"
			 alt="RSS feed" height="28" width="28" 
			 longdesc="/feed.xml"></a>
<span style="font-size:10px; float: right">Registered Charity Number 270429&nbsp;</span>
</div>