<br>Webmaster: Barbara Mackinder (<a href="/feedback.shtml">click here to give feedback</a>)
<span><a type="application/RSS+xml" href="/feed.xml" title="RSS feed"> 
  <img style="padding-right:0.3em;border:0;width:36px;height:14px"
	     src="/images/rss.gif"
			 title="RSS feed"
			 alt="RSS feed" height="14" width="36" 
			 longdesc="/feed.xml"></a></span>

<script src="http://www.geoplugin.net/javascript.gp" type="text/javascript"></script>
<script src="/incl/cookieControl-5.1.min.js" type="text/javascript"></script>
<script type="text/javascript">//<![CDATA[
  cookieControl({
      introText:'This site uses some unobtrusive cookies to store information on your computer.',
      fullText:'<p>We use some non-essential cookies to anonymously track visitors or enhance your experience of the site. If you\'re not happy with this, we won\'t set these cookies but some nice features of the site may be unavailable.</p><p>To control third party cookies, you can also adjust your <a href="http://www.civicuk.com/cookie-law/browser-settings" target="_blank">browser settings</a>.</p><p>By using our site you accept the terms of our <a href="http://www.systass.org/cookies.shtml">Privacy Policy</a>.</p>',
      position:'left', // left or right
      shape:'triangle', // triangle or diamond
      theme:'light', // light or dark
      startOpen:true,
      autoHide:6000,
      subdomains:true,
      protectedCookies: ['analytics', 'twitter'], //list the cookies you do not want deleted ['analytics', 'twitter']
      consentModel:'information_only',
      onAccept:function(){ccAddAnalytics()},
      onReady:function(){},
      onCookiesAllowed:function(){ccAddAnalytics()},
      onCookiesNotAllowed:function(){},
      countries:'United Kingdom' // Or supply a list ['United Kingdom', 'Greece']
      });

      function ccAddAnalytics() {
        jQuery.getScript("http://www.google-analytics.com/ga.js", function() {
          var GATracker = _gat._createTracker('');
          GATracker._trackPageview();
        });
      }
   //]]>
</script>  


