<a name="Bath_Studentships"></a>
<div style="float: right; margin-left: 5px;"><img src="http://www.systass.org/images/leverhulme-logo.jpg" width="160" height="80" alt="Leverhulme Trust" title="Leverhulme Trust" /></div>
<p class="title">Two Leverhulme funded PhD Studentships in the Department of Biology and Biochemistry, University of Bath</p>
<p><strong>Applications are invited for a studentship on Fossils and the Tree of Life.</strong></p>
<ul>
<li>Can we infer the true Tree of Life without fossils?</li>
<li>Are fossil characters phylogenetically biased, and if so, does it matter?</li>
<li>Is the phylogeny of some groups really much more intractable than others?</li>
<li>Are ghost ranges much more common in some groups, and if so, why?</li>
</ul>
<p>Closing Date: 18 May 2009<br>
<a href="/news/PhD_Studentship_Fossils_and_the_Tree_of_Life.pdf">Further details</a></p>

<p><strong>Applications are invited for a studentship on Macroevolutionary Trends.</strong></p>
<ul>
<li>Is the early evolution of maximal disparity of form a rule?</li>
<li>Do clades go extinct because better-adapted ones displace them?</li>
<li>Is increasing complexity in animal groups inevitable?</li>
<li>Are reductions in complexity misleading phylogenetic analyses?</li>
</ul>
<p>Closing Date: 18 May 2009<br>
<a href="/news/PhD_Studentship_Macroevolutionary_Trends.pdf">Further details</a></p>