<a name="BiodiversityPolicyLecture2011"></a>
<p class="title"><em>Joint Biodiversity Policy Lecture with Linnean Society</em></p>
<p class="title">Seeing REDD: Science, Policy and Politics in Biodiversity and Climate Change.</p>
<p class="title">Peter Bridgewater, Chair JNCC</p>
<p class="title">14th April 2011, 6.00pm.  The Linnean Society</p>

<div style="float: left; margin-right: 5px;"><img src="http://www.systass.org/images/PeterBridgewater.jpg" alt="Dr. Peter Bridgewater" title="Dr. Peter Bridgewater" height="123" width="98"></div>

<p>In late October 2010 The Convention on Biological Diversity held its tenth meeting, 
regarded as successfully achieving a new target for 2020, having missed the target 
set for 2010.  As the abstract is being written preparations are in hand for the 
16the meeting of the Framework Convention on climate Change, to be held in Cancun, 
December 2010.  A key issue for both conventions is that of Reducing Emissions (of 
carbon) from Deforestation and (forest) degradation (REDD).  This has morphed to REDD+ 
in recent discussions, where the plus includes conservation measures for forests.  
This has led to discussions about where the discussions and decisions on forest, 
carbon and biodiversity should be conducted within the UN system.  And it ignores 
the inconvenient truth that while forests are a significant carbon moderator there 
are other ecosystems on earth!  This lecture will explore the links between biodiversity 
and climate change, the avenues for sensible national and international discussion 
and the likely policy outcomes for biodiversity in the coming decades.</p>

<p>Tea will be served in the Library from 5.30pm and the lecture will be followed 
by a wine reception.  This meeting is free and open to all; registration is not necessary.</p>
