<p class="title">Beyond Cladistics: A Festschrift for Chris Humphries</p>

<p class="title">1st to 3rd of October 2008, at the Linnean Society</p>

<div style="float: left; margin-right: 5px;"><img src="http://www.systass.org/images/Chris-Humphries.png" alt="Prof. Chris Humphries" title="Prof. Chris Humphries" height="280" width="235"></div>

<p>As an approach to the discovery of phylogenetic relationships among organisms, cladistics 
took the systematics community by storm. According to David Hull, in his 1988 account 
of its history, cladistics was winning out everywhere; according to Colin Patterson, 
cladistics "began in the late 1960s, accelerated in the 1970s, and was virtually complete 
by the eighties"; in contrast, Gareth Nelson suggested that cladistics is suffering from 
"Arrested Development". This symposium, entitled Beyond Cladistics, in honour of botanist 
Chris Humphries, will address some general issues relating to cladistics: its past, its 
present and its future - if, indeed, there is anything beyond cladistics itself.</p>


<p>Additional Information</p>
<ul>
<li><a href="http://www.linnean.org/fileadmin/events2/attachments/1215508009_Chris%20Humphries%20Programme.pdf" rel="external">Programme</a></li>
<li><a href="http://www.linnean.org/fileadmin/events2/attachments/1215508015_Chris%20Humphries%20Registration%20Form.pdf" rel="external">Registration Form</a></li>
</ul>
