<p class="title">Professor Christopher J. Humphries, 1947-2009</p>

<div style="float: left; margin-right: 5px;"><img src="http://www.systass.org/images/Chris-Humphries.png" alt="Prof. Chris Humphries" title="Prof. Chris Humphries" height="280" width="235"></div>

<p>It is often the sad task of a President to report the death of a past-President, 
but it is rare that the two incumbencies in question are separated by as little 
as three years. The fact that Chris Humphries had been ailing for some time, suffering 
from heart problems and having survived (barely) a liver transplant, in no way lessened 
the blow of his death on July 31st, at the ridiculously young age of 62. The recent 
publication by Chris's long-time colleagues at the Natural History Museum, David 
Williams and Charlie Jarvis, of an excellent factual obituary for Chris 
(<a href="www.telegraph.co.uk/news/obituaries/science-obituaries/6039183/Chris-Humphries" rel="external">www.telegraph.co.uk/news/obituaries/science-obituaries/6039183/Chris-Humphries</a>) 
leaves me free to pen a more personal valediction.</p>

<p>I first met Chris in the early 1980s, when he was arguably at the height of his 
very considerable powers. During the previous decade he had played a key role in 
catalysing the cladistics revolution, alongside such luminaries as Colin Patterson. 
Together with K&aring;re Bremer and Vicki Funk, he had successfully promoted new-fangled 
cladistic methods of phylogeny reconstruction within the botanical community. Having 
laid these essential foundations, he then explored the full range of biologically 
relevant applications to which parsimony could be applied, rattling off in short 
order co-authored or edited volumes on ontogeny, biogeography and conservation prioritisation 
before co-authoring a classic textbook on cladistic methods. All of these books 
justly became classics. Supported by numerous well-cited peer-reviewed papers and 
conference talks across the globe, these outputs undoubtedly had a profound impact 
throughout systematic biology.</p>

<p>Plaudits for Chris's pioneering intellect came relatively rapidly within the expanding 
cladistics field, leading to extensive citation and the Presidency of the Willi Hennig 
Society in 1989-91. However, bouquets arrived rather more slowly from the wider 
systematics/taxonomic community, which was not entirely certain that it wished to 
entertain this growing cadre of fractious young(ish) whippersnappers with their 
logical rigour, complex terminology and often aggressive proselytising. Nevertheless, 
Chris was soon warmly regarded in both the Linnean Society and the Systematics Association. 
His Vice-Presidency of the Linnean Society (1994-8) was followed by the Presidency 
of the Systematics Association (2000-3) and the award of the Linnean Gold Medal 
(2001), together reflecting the mutually beneficial symbiosis that existed between 
Chris and both organisations. He was also awarded a visiting Chair and Individual 
Merit status by BBSRC. Many of us felt that Fellowship of the Royal Society would 
have been just reward for his earlier innovations, but this goal was probably made 
more difficult by Chris's admirable combination of certainty of purpose and disarming 
honesty (anyone doubting either quality should, for example, consult Chris's critical 
analysis of the SA Biennial conference over which he presided in South Kensington 
in 2001: <em>Systematist</em> 18 (January 2002), pp. 1-3).</p>  

<p>Chris was, in addition, a committed bon viveur and genuine polymath. The depth and 
breadth of his general knowledge was breathtaking; it was a brave person who challenged 
Chris on topics as disparate as the history of science on the one hand versus modern 
art or jazz on the other. I used to chide Chris that the one topic for which he rarely 
found sufficient time was botany itself, but in truth, he viewed educating people 
as a higher calling. He would boldly inform senior (sometimes dangerously senior) 
colleagues of the error of their ways if they had not yet subscribed to hard-core 
cladistics. The roll-call of junior colleagues who benefited considerably from Chris's 
boundless advice and encouragement is long and ultimately prestigious - like Miss 
Jean Brodie, Chris had the ability and charisma to acquire many life-long prot&eacute;g&eacute;s. 
Moreover, unlike Miss Jean Brodie, Chris was happy to interact with the wider populus; 
the tower in which he resided in later years at the Natural History Museum was certainly 
not built of ivory.</p>

<p>So, I return full circle to recount my earliest meetings with Chris, which occurred 
when I was a part-time undergraduate (and committed pheneticist) determined on pursuing 
a career in sedimentary geology. The encounters did not take place in pubs or involve 
drafting indecipherable diagrams on the backs of beer mats - that came later. No, 
I first met Chris in the herbarium of the Natural History Museum at its centenary 
exhibition in 1981. Bracketed by expositions of phenetics and authoritarian evolutionary 
scenarios, Chris was selling cladistic methods with the style and vigour of a Pettycoat 
Lane stallholder. Once lured to his stall I was treated by Chris to a thick wad of 
photocopied articles from <em>Nature</em> detailing the furore caused by the Museum's recent 
switch to cladistics-dominated exhibits. Scratching my head over these peculiar articles 
on the train back to St Albans, I decided that I wanted to know more. Thus, the scene 
moved to the Friends Meeting House in Hemel Hempstead, one Saturday afternoon several 
months later, where Chris had kindly agreed to lecture the heterogeneous membership 
of the Hertfordshire Natural History Society on the importance of recognising that 
the lungfish and the cow are more closely related to each other than either is to 
the salmon.</p>

<p>Few authorities of Chris's calibre would have wasted their valuable time on such 
a parochial gathering, yet his enthusiasm and commitment shone through and thereby 
nudged my professional life in a subtly different, yet irrevocable, direction. I 
am confident that Chris's influence on both systematics and systematists was - and 
remains - profound.</p>

<p>Richard Bateman</p>

