<a name="JohnBeddington"></a>
<p class="title">The Second Annual Biodiversity Policy Lecture in Association with the Systematics Association</p>
<p class="title">16 April 2009, 6:00pm at the Linnean Society</p>
<p class="title">Biodiversity in a Changing World</p>
<p>Professor John Beddington, Government Chief Scientific Adviser and 
Head of the Government Office for Science</p>
<div style="float: right; margin-left: 5px;"><img src="/images/JohnBeddington.jpg" width="85" height="100" alt="Prof. John Beddington" title="Prof. John Beddington" /></div>
<p>Prof John Beddington will deliver a talk on biodiversity in a changing world, which 
will include the interrelated issues of climate change, food, water and energy security. 
He will also discuss the importance of understanding biodiversity further, which 
amongst other things will help the UK Government in its efforts to meet its national 
and international biodiversity policy targets.</p>

<p class="title">Registration for this event is essential, please contact Kate Longhurst 
to book a place:
<script type="text/javascript"><!--
  var usr = "kate";
  var dom = "linnean";
  var tld = "org";
  var ady = usr + "@" + dom + "." + tld;
  document.write("<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>")
//--></script></p>

<p>Tea will be served in the Library from 5.30pm and the lecture will be followed 
by a wine reception.</p>
