<p>Dear Colleague,<br>
My name is Josephine Hill and I am a Master's student in Biosystematics at The Natural History
Museum. I am inviting you participate in my first research project exploring character quality in
phylogeny reconstruction.</p>
<p>Recently, there has been much debate as to whether molecular, morphological and even behavioural
information differ in quality. For example, does one type of character contain more 'homoplasy' or
convergence than another type of character? As part of my first project I wish to survey the opinion of
scientists from different fields of research as to whether molecular, morphological and behavioural
information differ in quality. I hope the results will give me a greater understanding of any association
between area of interest and the reasoning behind personal preference.</p>

<!-- <p>Attached in a <a href="JosephineHillQuestionnaire.doc">short questionnaire</a> which should take no longer than twenty minutes to complete. There
is no obligation to complete the survey; however your responses will not be identified with you
personally and will be kept confidential. If possible, please complete and return by the <strong>1st February 2008</strong> and
indicate if you wish for a copy of the results.</p> -->

<p style="background-color: #cc6633">The survey date has now passed.</p>

<p>I thank you in advance and please contact me if you have any further queries regarding this study.<br>
Yours sincerely<br>
Josephine<br>
Email: 
<script type="text/javascript"><!--
  var usr = "Josephine.hill07";
  var dom = "imperial.ac";
  var tld = "uk";
  var ady = usr + "@" + dom + "." + tld;
  document.write("<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>")
//--></script><br>
<!-- Download: <a href="JosephineHillCoverLetter.pdf">This cover letter</a> | <a href="JosephineHillQuestionnaire.doc">The questionnaire</a><br> --> 
</p>
