<a name="Kew_250"></a>
<p class="title">Plant conservation for the next decade: a celebration of Kew's 250th anniversary</p>
<p>October 12th-16th, 2009</p>
<p>Royal Botanic Gardens, Kew</p>

<p><a href="http://www.kew.org/science/anniversary-conference/" rel="external">www.kew.org/science/anniversary-conference/</a></p>

<p class="title">Call for Papers</p>



<div style="float: right; margin-left: 5px;"><img src="http://www.kew.org/science/anniversary-conference/design/Pictures/Home1.jpg" width="300" height="225" alt="Palm House, RBG Kew" title="Palm House, RBG Kew" /></div>
<p>The Royal Botanic Gardens, Kew is hosting a celebratory scientific conference 
from October 12th-16th 2009, to mark the occasion of its 250th Anniversary. The programme 
will include three days of scientific sessions in the Jodrell laboratory, showcasing Kew's 
conservation research and inviting leading international research scientists to present 
papers in six sessions entitled:</p>

<ul>
<li>Plant conservation: policies and politics</li> 
<li>Plant conservation: management and restoration</li>
<li>Plant conservation and human cultures</li>
<li>Plant conservation and agriculture</li>
<li>Frontiers of plant conservation technology</li>
<li>Plant conservation: what can we afford to lose?</li>
</ul>

<p>Keynote speakers include Dr Peter Raven, Dr Judy West, Professor Hongwen Huang, 
Professor Michael E Kane, Dr Saw Leng Guan, Professor Richard Hobbs, Ms Sara Oldfield, 
the current Director of Kew Professor Stephen Hopper and previous Directors Professor 
Sir Peter Crane and Professor Sir Ghillean Prance.</p>

<p>We now invite interested parties to submit abstracts for posters and oral presentations, 
to be considered for inclusion in this exciting conference. Participating authors 
are also invited to contribute to a special issue of Kew Bulletin, subject to standard 
scientific review. </p>

<p>Abstracts should be no longer than 250 words, excluding the title, and the deadline 
for abstract submission is April 9th, 2009. Details of online abstract submission 
and registration, and general information about the conference, can be found at: </p>

<p><a href="http://www.kew.org/science/anniversary-conference/" rel="external">www.kew.org/science/anniversary-conference/</a></p>
