<a name="Niche_Evolution"></a>
<p class="title">NICHE EVOLUTION</p>
<p>A unifying concept for systematics, ecology, palaeontology and conservation biology</p>
<p>3-4 July, 2009. Excursion on 5 July.</p>
<p>Zurich, Switzerland</p>

<p><a href="http://www.systbot.uzh.ch/niche/" rel="external">www.systbot.uzh.ch/niche</a></p>

<p><strong>MOTIVATION</strong><br>Evolution of ecological niches, in their various 
guises, has become a central theme in several research fields of biology. We argue 
that niches, how they evolve, and the consequences of their evolution, affect a wide 
range of disciplines in organismal and evolutionary biology, and as such could be 
seen as a unifying thread.</p>
 
<p>In this meeting we will explore the interdisciplinary impact of evolving niches, 
and so bring together systematists, invasion biologists, biodiversity specialists, 
ecologists, and palaeontologists. We want to explore the commonality of evolving 
niches. The focus is more on concepts than methods (although, of course, the methods 
used will impact massively on the concepts). The emphasis is more on how to understand 
the evolution of a niche, rather than the definition of the niche. There will be 
some talks on the basics of niches to set the stage for the topics of niche evolution. 
The idea is to bring people together working in this field and to provide a forum 
to discuss developments, prospects and needs with various users and specialists. 
Therefore, the program is structured to provide ample time for discussions between 
and after the sessions.</p>

<p><strong>PLACE</strong><br />The meeting will take place at the Institute of Systematic 
Botany of the University of Zurich, situated in the botanical garden of the University 
of Zurich, within easy reach of public transport.</p>

<p><strong>TALKS</strong><br />Only invited talks will be given, and contributions 
as posters are welcome. There will be an evening poster session.</p>
 

<p>Invited speakers include William Bond, Jeannine Cavender-Bares, Alastair Culham, 
Catherine Graham, Antoine Guisan, Sabine Jakob, Jennifer Lau, Peter Linder, Signe 
Normand, Peter Pearman, Townsend Peterson, Bob Ricklefs, Nicolas Salamin, Walter 
Salzburger, Harald Schneider, Jonathan Silvertown, Wilfried Thuillier and Niklaus 
Zimmermann.</p>
 
<p><strong>POST-CONFERENCE ONE-DAY EXCURSION</strong><br />There will be an excursion 
for Sunday, 5 July, into the Alps. We will cross the Susten Pass (2'250 m). On Susten 
Pass we will visit the Steingletscher glacier, which has shown a dramatic reduction 
in the past decades, thus exposing much new habitat. We will be able to see the plant 
successions into these newly exposed habitats. This shows very dramatically the effect 
of climate change, and the potential new habitats exposed.</p>
 
<p><strong>ORGANISERS</strong><br />Peter Linder, Alexandre Antonelli, Rafael Wüest 
(Systematic Botany, University of Zurich), Niklaus Zimmermann and Peter Pearman 
(Institute of Forest, Snow and Landscape Research, WSL, Zurich), Harald Schneider 
(Natural History Museum, London), Frank Blattner (IPK Gatersleben) and Nicolas Salamin 
(Computational Phylogenetics, University of Lausanne)</p>

<p><strong>REGISTRATION IS OPEN</strong>, at <a href="http://www.systbot.uzh.ch/niche/" rel="external">www.systbot.uzh.ch/niche</a></p>

<p>Dr Alexandre Antonelli<br />
Institute of Systematic Botany<br />
Zollikerstrasse 107<br />
CH 8008  Z&uuml;rich<br />
Switzerland<br />
Ph: +41 (0)44 634 8416<br />
Fax: +41 (0)44 634 8403<br />
		<script type="text/javascript"><!--
    var usr = "alexandre.antonelli";
    var dom = "systbot.uzh";
    var tld = "ch";
    var ady = usr + "@" + dom + "." + tld;
    document.write("<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>")
    //--></script></p>
