<p class="title">Launch of the Systematics & Taxonomy (SynTax) Research Scheme</p>

<p class="title">12th of November 2009, 6.00pm</p>

<p class="title">The Linnean Society of London</p>

<p>The Research Councils are launching a new funding scheme for research in systematics 
and taxonomy.  The Systematics and Taxonomy (SynTax) scheme is designed to provide 
short-term funding for preliminary research that will form the basis of novel responsive 
mode proposals with a substantial systematics/taxonomy component.</p>

<p>The scheme aims to stimulate high quality taxonomy and systematics-related research 
proposals to the UK's Research Councils.  The scheme follows on from the Collaborative 
Systematics (CoSyst) scheme, through which a number of projects have gone on to receive 
responsive mode funding.  The launch event will provide details of the SynTax scheme 
and will showcase successful projects funded under its predecessor CoSyst.</p>

<p class="title">Speakers</p>

<p>SynTax Scheme</p>

<p>Amanda Read, BBSRC</p>

 
<p class="title">CoSyst Showcase:</p>

<ul>
<li>Genomic tools for studying the Origin of Species<br>
Professor Vincent Savolainen, Imperial College London</li>

<li>Hydatellaceae:  a key to reassessing morphological evolution in angiosperms<br>
Dr Paula Rudall, Royal Botanic Gardens Kew</li>

<li>Molecular diversity of microbial eukaryotes using a large-scale parallel tag sequencing strategy<br>
Dr Tom Richards, University of Exeter</li>
</ul>

<p>Posters are invited from CoSyst grantholders.</p>

<p>Tea will be served in the Library from 5.30pm and the lecture will be followed 
by a wine reception and poster session.  This meeting is <strong>free</strong> and open to all; <strong>registration 
is not necessary</strong>.</p>
