	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
		<li><img src="/biennial2015/accom-images/christchurchmain.jpg" alt="Tom Tower and Quad - Christ Church" title="Tom Tower and Quad - Christ Church" id="wows1_0"/></li>
		<li><img src="/biennial2015/accom-images/christchurchhall.jpg" alt="The Great Hall Christ Church" title="The Great Hall Christ Church" id="wows1_1"/></li>
		<li><img src="/biennial2015/accom-images/singleensuite_1.jpg" alt="Single Ensuite 1" title="Single Ensuite 1" id="wows1_2"/></li>
		<li><img src="/biennial2015/accom-images/singleensuite_2.jpg" alt="Single Ensuite 2" title="Single Ensuite 2" id="wows1_3"/></li>
		<li><a href="http://wowslider.com/vf"><img src="/biennial2015/accom-images/twinensuite.jpg" alt="full screen slider" title="Twin Ensuite" id="wows1_4"/></a></li>
		<li><img src="/biennial2015/accom-images/twinstandardset.jpg" alt="Twin Standard set" title="Twin Standard set" id="wows1_5"/></li>
	</ul></div>
	<span class="wsl"><a href="http://wowslider.com/vu">image carousel</a> by WOWSlider.com v6.8</span>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="/biennial2015/accom-engine1/wowslider.js"></script>
	<script type="text/javascript" src="/biennial2015/accom-engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
