<div style="clear:both"></div>
<hr>
<p class="title">Conference Banquet: The Great Hall, Christ Church</p>
<p><strong>Thursday 27 August</strong> tickets can be booked via the <a href="http://www.oxforduniversitystores.co.uk/browse/extra_info.asp?compid=1&modid=2&deptid=187&catid=119&prodid=299" rel="external" title="Registration is provided by an external site">Oxford site</a></p>
<img src="GreatHallChristChurch.jpg" width="250" height="166" alt="GreatHallChristChurch (46K)" />
<p>Follow the footsteps of the world's favourite wizard through Oxford's most spectacular 
College. Many of the scenes in the Harry Potter feature films are shot in various 
locations of the College.  The conference banquet takes place in The Great Hall 
(photograph above) which was replicated in the film studios to create Hogwart's Hall.
Source: <a href="http://www.chch.ox.ac.uk/" rel="external">Christ Church College</a></p>


<p class="title">After dinner speaker: Dr. George McGavin</p>

<img src="GeorgeMcGavin.jpg" width="312" height="175" alt="George McGavin - Source: BBC George McGavin's wildlife challenge"  title="George McGavin - Source: BBC George McGavin's wildlife challenge"/>
<p>Dr George McGavin is an Honorary Research Associate at the Oxford University 
Museum of Natural History and a Research Associate of The Department of Zoology 
of Oxford University.</p>
<p>His research has taken him from the tropical forests of Papua New Guinea to the 
caves of Thailand and from the jungles of Belize to the savannas of Tanzania. George 
studied Zoology at Edinburgh University before completing a doctorate at the British 
Museum of Natural History and Imperial College, London. George has written numerous 
books on insects and other animals. As well as being a regular contributer to <em>The One Show</em> 
(BBC1) George has made several programmes for the BBC including <em>The Lost Lands...</em>, 
<em>Monkey Planet</em> and <em>Minature Britain</em>.  
Source: <a href="http://www.jowandermanagement.com/clients/georgemcgavin.php" rel="external">jowandermanagement.com</a></p>
