<p>The six students who were selected to receive a Linnean Society of London Student Bursary of &pound;200 to attend the meeting are:</p>
<table summary="Linnean Society Student Bursaries">
<tr><th>Name</th><td>Organisation</td><td>Contributed paper</td></tr>
<tr><th>Bernardo Santos</th>	<td>Richard Gilder Graduate School - American Museum of Natural History, United States</td>	<td>Evolution of convergent functional systems in a speciose clade of parasitic wasps (Ichneumonidae, Cryptinae)</td></tr>
<tr><th>Liza G&oacute;mez Daglio</th>	<td>University of California, Merced, United States</td>	<td>Species discovery and integrative taxonomy in jellyfishes (Cnidaria, Discomedusae)</td></tr>
<tr><th>Marina Bonfim Santos</th>	<td>Naturalis Biodiversity Center/Leiden University, Netherlands</td>	<td>Evolution of the leucobryoid morphology in Dicranidae (Bryophyta)</td></tr>
<tr><th>Donald Davesne</th>	<td>Mus&eacute;um national d'Histoire naturelle, France</td>	<td>Fossils increase congruence between molecular and morphological hypotheses of spiny-rayed teleost (Acanthomorpha) phylogeny</td></tr>
<tr><th>Guy Atchison</th>	<td>University of Z&uuml;rich, Switzerland</td>	<td>Accelerating integrative taxonomy in the genomics era: RADseq provides unprecedented species resolution in the genus <em>Lupinus</em> (Leguminosae)</td></tr>
<tr><th>Steven Dodsworth</th>	<td>Queen Mary University of London, United Kingdom</td>	<td>Genome skimming and phylogenomics of <em>Nicotiana</em> sect. Suaveolentes (Solanaceae)</td></tr>
</table> 
