<table summary="Programme">
<tr><th>09.00</th> 
<td>Registration</td><td>&nbsp;</td></tr>

<tr><th>09.35</th> 
<td>Introduction</td><td>Juliet Brodie (NHM)</td></tr>

<tr><th>09.40</th>
<td>Welcome and introduction</td><td>Tim Barraclough (Imperial College)</td></tr>

<tr><th>09.50</th>
<td><em><strong>Andrea Crowther</strong></em></td>
<td>Taxonomic uncertainty in the sea anemone genus <em>Lebrunia</em></td></tr>

<tr><th>10.10</th>
<td><em><strong>Ellen Cocquyt</strong></em></td>
<td>Phylogenetic relationships of the green algae refined: new insights from a combined analysis of nuclear and plastid genes</td></tr> 

<tr><th>10.30</th>
<td><em><strong>Magdalena Zarowiecki</strong></em></td>
<td>Investigating evidence that the mosquito <em>An. vagus</em> is a cryptic species complex</td></tr>

<tr><th>10.50</th> 
<td><em><strong>Sognigb&eacute; N'Danikou</strong></em></td>
<td>Phenetic analysis of Wild populations of <em>Momordica charantia</em> L. (Cucurbitaceae) in West Africa and inference of the definition of the new subspecies <em>M. c. macroloba</em> Achigan-Dako &amp; Blattner</td></tr>

<tr><th>11.10</th>
<td>Tea, coffee and posters</td><td>&nbsp;</td></tr>

<tr><th>11.40</th>
<td><em><strong>Therese Holton</strong></em></td>
<td>Phylogenomic reconstruction of the Metazoa</td></tr>

<tr><th>12.00</th>
<td><em><strong>Lucy Bittner</strong></em></td>
<td>Unravelling diversity of crustose (non-geniculate) coralline algae of the South Pacific</td></tr>

<tr><th>12.20</th> 
<td><em><strong>John Wilson</strong></em></td>
<td>Comparison of DNA barcode readers for the identifications of butterflies</td></tr>

<tr><th>12.40</th> 
<td><em><strong>Alba Verg&eacute;s</strong></em></td>
<td>The genus <em>Kallymenia</em> (Kallymeniaceae, Rhodophyta) from the north-eastern Atlantic</td></tr>

<tr><th>13.00</th>
<td>Lunch and posters</td></tr>

<tr><th>14.00</th>
<td><em><strong>Claire Standley</strong></em></td>
<td>On the trail of a snail: elucidating the species complexes of East African <em>Biomphalaria</em></td></tr>

<tr><th>14.20</th>
<td><em><strong>Mine Kocyigit</strong></em></td>
<td>A phylogenetic analysis of <em>Allium</em> sect. <em>Codonoprasum</em> (Alliaceae) using TRNL-F plastid and its nuclear DNA sequences</td></tr>

<tr><th>14.40</th>
<td><em><strong>Rachel Walker</strong></em></td>
<td>The evolution and development of specialised floral traits in the South African 'beetle daisy' <em>Gorteria diffusa</em> Thunb.</td></tr>

<tr><th>15.00</th>
<td><em><strong>Romina Novo Henriques</strong></em></td>
<td>The influence of the Benguela cold current system in the genetic substructure of four fish species</td></tr>

<tr><th>15.20</th>
<td>Tea and posters</td></tr>

<tr><th>15.50</th>
<td><em><strong>Hanno Schaefer</strong></em></td>
<td>Systematics of <em>Cucumis</em> (Cucurbitaceae) and the origin of melon and cucumber</td></tr>

<tr><th>16.10</th>
<td><em><strong>Katie Davis</strong></em></td>
<td>A species-level supertree of birds and the future of supertree construction</td></tr>

<tr><th>16.30</th>
<td><em><strong>Noem&iacute; S&aacute;nchez</strong></em></td>
<td>Critical taxonomic features of the genus <em>Gloiocladia</em> (Faucheaceae, Rhodophyta)</td></tr>

<tr><th>16.50</th>
<td><em><strong>Claudia Ciotir</strong></em></td>
<td>DNA barcoding outcomes from testing four plastid regions in <em>Cyclamen</em> L. (Myrsinaceae)</td></tr>

<tr><th>17.10</th>
<td>Closing comments and presentation of prizes for best oral and poster presentations</td><td>Peter Olson (NHM)</td></tr>

<tr><th>17.25 - 19.00</th>  <td>Reception and Posters</td></tr>
</table>
