<p>Correct as of 19 November 2012 (v.4)</p>
<table summary="Programme v4">
<tr><th>08.30</th> 
<td>Registration</td><td>(Please put posters up as early as possible from 08.30)</td></tr>

<tr><th>09.30</th> 
<td colspan="2"><strong>Welcome	YSF team</strong></td></tr>

<tr><th>09.40</th> 
<td>Claire R. Peart</td><td>Biodiversity and evolutionary relationships of Claroteid catfish from Lake Tanganyika</td></tr>

<tr><th>09.58</th> 
<td>Marylaure de la Harpe</td><td>Do genetic, geographical or ecological factors play a major role in the distribution of the Western European <em>Alyssum montanum</em> polyploid complex?</td></tr>

<tr><th>10.16</th> 
<td>Patrick Knopf</td><td>Origin and phylogeny of Podocarpaceae (Coniferopsida)</td></tr>

<tr><th>10.34</th> 
<td>Bhanubong Bongchewin</td><td>A phylogenetic study of the tribe Gomphostemmateae Scheen &amp; Lindqvist (Lamiaceae)</td></tr>

<tr><th>10.52</th> 
<td colspan="2"><em>Coffee and attended posters</em> (even numbers)</td></tr>
	
<tr><th>11.30</th> 
<td>Simon Maddock</td><td>Living in Paradise: systematics and biogeography of Seychelles amphibians</td></tr>

<tr><th>11.48</th> 
<td>Karen Siu Ting</td><td>Taxonomic placement of <em>Ericabatrachus baleensis</em> (Amphibia: Anura: Ranoidea) and a proposal for inclusion of data in phylogenetic analyses.</td></tr>

<tr><th>12.06</th> 
<td>Sarah Parks</td><td>The effect of long branches on Maximum Likelihood tree reconstruction</td></tr>

<tr><th>12.24</th> 
<td>Wasiu A. Akanni</td><td>Developing a Maximum Likelihood and Bayesian supertree</td></tr>

<tr><th>12.42</th> 
<td>Ana&iuml;s Grand</td><td>3ia swims with the fishes: a comparison of 3ia and parsimony phylogenies of Gadiform fishes</td></tr>

<tr><th>13.00</th> 
<td colspan="2"><strong>Lunch and posters</strong></td></tr>
	
<tr><th>14.00</th> 
<td>Richard S. Thompson</td><td>Locked in the bones: the production of a large molecular systematic dataset from museum specimens.</td></tr>

<tr><th>14.18</th> 
<td>Bethany Williams</td><td>Foundation Monograph of <em>Convolvulus</em></td></tr>

<tr><th>14.36</th> 
<td>Haris Saslis-Lagourdakis</td><td>Phylogenies reveal predictive power of traditional medicine in bioprospecting</td></tr>

<tr><th>14.54</th> 
<td>Zo&euml; Goodwin</td><td>Species discovery in <em>Aframomum</em></td></tr>

<tr><th>15.12</th> 
<td colspan="2"><strong>Tea and attended posters</strong> (odd numbers)</td></tr>
	
<tr><th>15.50</th> 
<td>Nicola Susanne Heckeberg</td><td>How combining morphological and molecular data improves positioning of fossil taxa in cervid (Ruminantia, Artiodactyla) phylogenies</td></tr>
 
<tr><th>16.08</th> 
<td>S&eacute;rgio Henriques</td><td>The advantages and challenges to the study of camel spiders (Solifugae, Arachnida).</td></tr>

<tr><th>16.26</th> 
<td>Krzysztof M. Kozak</td><td>Marker incongruence and signal consistency in the hyperdiverse <em>Heliconius</em> butterflies (Lepidoptera: Nymphalidae)</td></tr>

<tr><th>16.44</th> 
<td>Ana Rita Mendes</td><td>The <em>Myosotella 'myosotis-denticulata'</em> complex: untying a morphological knot</td></tr>

<tr><th>17.02</th> 
<td>Martin R. Smith</td><td>Deep molluscan relationships: reconciling morphology and molecules</td></tr>

<tr><th>17.20</th> 
<td colspan="2"><strong>Poster session</strong></td></tr>
	
<tr><th>18.00 - 19.00</th>
<td colspan="2"><strong>Presentation of Prizes and Reception</strong>	Robert Scotland/Maria Vorontsova</td></tr>

</table>
