<table summary="Programme">
<tr><th>09.00</th> 
<td>Registration</td><td>&nbsp;</td></tr>

<tr><th>09.35</th> 
<td>Introduction</td><td>Juliet Brodie (NHM)</td></tr>

<tr><th>09.40</th>
<td>Welcome and introduction</td><td>Richard Bateman (President, Systematics Association)</td></tr>

<tr><th>09.50</th>
<td><em><strong>OM Grace</strong></em></td>
<td>Leaf chemistry in the systematics of <em>Aloe</em> L. (Alooideae)</td></tr>

<tr><th>10.10</th>
<td><em><strong>Rob Lanfear</strong></em></td>
<td>Metabolic rate does not calibrate the molecular clock</td></tr> 

<tr><th>10.30</th>
<td><em><strong>Rachel H Walker</strong></em></td>
<td>The taxonomy and biodiversity of articulated coralline algae in Britain and Ireland</td></tr>

<tr><th>10.50</th> 
<td><em><strong>Isabel Blasco-Costa</strong></em></td>
<td>Morphological and molecular circumscription and phylogenetic affinities of the 
digenean (<em>Platyhelminthes</em>) families Haploporidae and Haplosplanchnidae</td></tr>

<tr><th>11.10</th>
<td>Tea, coffee and posters</td><td>&nbsp;</td></tr>

<tr><th>11.40</th>
<td><em><strong>Caroline Byrne</strong></em></td>
<td>Phylogenetic revision of Thai Clusiaceae and Hypericaceae</td></tr>

<tr><th>12.00</th>
<td><em><strong>Victoria Svinti</strong></em></td>
<td>Detecting reassortment in influenza viruses</td></tr>

<tr><th>12.20</th> 
<td><em><strong>Peter Konstantinidis</strong></em></td>
<td>The monophyly of the <em>Gymnodontes</em></td></tr>

<tr><th>12.40</th> 
<td><em><strong>Jason Gibbs</strong></em></td>
<td>DNA barcoding phylogenies and the evolution of social parasitism in the bee subgenus <em>Dialictus</em> (Halictidae: Lasioglossum)</td></tr>

<tr><th>13.00</th>
<td>Lunch and posters</td></tr>

<tr><th>14.00</th>
<td><em><strong>Mark T Young</strong></em></td>
<td>Feeding biomechanics and the evolution of sauropodomorph dinosaurs</td></tr>

<tr><th>14.20</th>
<td><em><strong>Neela Enke</strong></em></td>
<td>Molecular phylogeny vs. morphology: contributions towards a new generic and infrageneric delimitation of <em>Crepis</em> L. (Cichorieae, Compositae)</td></tr>

<tr><th>14.40</th>
<td><em><strong>Fergal Martin</strong></em></td>
<td>Investigating the phylogenetic relationships of 27 completed YESS group genomes</td></tr>

<tr><th>15.00</th>
<td><em><strong>Katy Morgan</strong></em></td>
<td>Molecular phylogenetics and biogeography of the forest dependent <em>Leucosphyrus</em> Anopheles mosquitoes within Southeast Asia</td></tr>

<tr><th>15.20</th>
<td>Tea and posters</td></tr>

<tr><th>15.50</th>
<td><em><strong>Farah Ishtiaq</strong></em></td>
<td>Tracking host colonization with their blood parasites in South Pacific islands</td></tr>

<tr><th>16.10</th>
<td><em><strong>Angela McCann</strong></em></td>
<td>The tree of genomes: an empirical comparison of genome phylogeny reconstruction methods</td></tr>

<tr><th>16.30</th>
<td><em><strong>Emma Sherratt</strong></em></td>
<td>A geometric morphometric approach to comparative evolution of the caecilian skull</td></tr>

<tr><th>16.50</th>
<td><em><strong>Magalena Zarowiecki</strong></em></td>
<td>Ecological and geographical drivers of speciation in the <em>Anopheles sundaicus</em> (Diptera: Culicidae) species complex</td></tr>

<tr><th>17.10</th>
<td colspan="2">Closing comments and presentation of prizes for best oral and poster presentations</td></tr>

<tr><th>17.25 - 19.00</th>  <td colspan="2">Reception</td></tr>
</table>
