<p><strong>Abstracts</strong> must be submitted by e-mail in English no later than 
<strong>Friday 28 October 2016</strong> to <script type="text/javascript"><!--
  var usr = "YSF.SystematicsAssociation";
  var dom = "gmail";
  var tld = "com";
  var ady = usr + "@" + dom + "." + tld;
  document.write("(<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>)")
  //--></script>.  
The body text should not exceed 150 words in length. Title, authors, and their professional
affiliations should be included with the abstracts. If the presentation is co-authored,
the actual speaker (<em>oral</em>) or presenter (<em>poster</em>) must be clearly
indicated in <strong>BOLD</strong> text.</p>

<p>If you have presented a talk at the YSF before, we ask that you submit only for a poster
 presentation, as speaker slots are limited and we want to give as many people a chance
  as possible. Similarly, if you are presenting at both the YSF and MF, we ask that
   you not apply for speaking slots in both (or let us know so we can assess).</p>

<p>All registered attendants will receive by e-mail further information about the 
meeting, including abstracts, one week in advance. This information will also be
displayed on the Systematics Association website.</p>