<p><strong>Abstracts</strong> must be submitted by e-mail in English no later than 
<strong>Friday 23 October 2015</strong> to <script type="text/javascript"><!--
  var usr = "YSF.SystematicsAssociation";
  var dom = "gmail";
  var tld = "com";
  var ady = usr + "@" + dom + "." + tld;
  document.write("(<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>)")
  //--></script>.  
The body text should not exceed 150 words in length. If the presentation is co-authored, 
the actual speaker (<em>oral</em>) or presenter (<em>poster</em>) must be clearly 
indicated in <strong>BOLD</strong> text.</p>

<p>All registered attendants will receive by e-mail further information about the 
meeting, including abstracts, one week in advance.  This information will also be 
displayed on the Systematics Association website.</p>