<!-- include used for YSF announcement on homepage -->
<p class="title">9th Young Systematists' Forum.<br>Wed, 5 Dec 2007</p>
<div style="float: right; margin-left: 5px;"><a href="http://commons.wikimedia.org/wiki/Image:Natural_History_Museum_London_Jan_2006.jpg" rel="external" title="The Natural History Museum, by David Iliff"><img src="/ysf/NHM_David_Iliff.png" width="300" height="191" alt="The Natural History Museum, by David Iliff" style="border: none;" /></a></div>
<p>This well-established <a href="/ysf/index.shtml">event</a> provides an important 
opportunity for budding systematists to discuss their research in front of their peers 
within a supportive environment.</p>
<p>Visit the YSF page for <a href="/ysf/">further details</a>.</p>
<p style="background-color: #cc6633"><strong>Update:</strong>  The <a href="/ysf/index.shtml#Programme">Programme</a> and <a href="/ysf/index.shtml#Abstracts">Abstracts</a> are now available for download.</p>
