<p>You can also read the abstracts of the 
<a href="/ysf/15th(2013)_YSF_Abstract_Booklet.pdf">15th (2013)</a>,
<a href="/ysf/14th(2012)_YSF_Abstract_Booklet.pdf">14th (2012)</a>,
<a href="/ysf/13th(2011)_YSF_Abstract_Booklet.pdf">13th (2011)</a>,
<a href="/ysf/12th(2010)_YSF_Abstract_Booklet.pdf">12th (2010)</a>, 
<a href="/ysf/11th_YSF_Abstract_Booklet.pdf">11th (2009)</a>, 
<a href="/ysf/10th_YSF_FINAL.pdf">10th (2008)</a>, 
<a href="/ysf/9th_YSF.pdf">9th (2007)</a>, 
<a href="/ysf/8th_YSF.pdf">8th (2006)</a>, 
<a href="/ysf/6th_YSF.pdf">6th (2004)</a>, 
<a href="/ysf/5th_YSF.pdf">5th (2003)</a>, 
<a href="/ysf/4th_YSF.pdf">4th (2002)</a> and 
<a href="/ysf/3rd_YSF.pdf">3rd (2000)</a> YSF.</p>
