        <hr>
											
        <p class="title">
          <a href="https://twitter.com/hashtag/ysf2014?f=realtime" style=
          "background: transparent; text-decoration: none;padding-right: 0px;"
          rel="external" title="official hashtag #YSY2014">#YSF2014</a>
        </p>
        <div class="textsmall">
          <p>
            Young Systematists' Forum details are out, an exciting opportunity 
						for early career scientists to present their data.<br>
						<a href="/ysf/16th(2014)YSF_Abstract_Booklet_v2.pdf" rel="external">Download abstracts and programme</a> or     
						<a href="http://systass.org/ysf/">find out more</a>.
          </p>
        </div>
