<p>Registration is <strong>FREE</strong>.  Send applications by e-mail to 

<script type="text/javascript"><!--
  var usr = "YSF.SystematicsAssociation";
  var dom = "gmail";
  var tld = "com";
  var ady = usr + "@" + dom + "." + tld;
  document.write("(<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>)")
  //--></script>, supplying your name, contact address and stating whether or not 
you wish to give an oral or poster presentation. Space will be allocated subject 
to availability and for a balanced programme of animal, plant, algal, molecular 
and other research.</p><p>Non-participating attendees are also very welcome - please 
register as above.</p>
