<p>Registration is <strong>FREE</strong> and still open to non-participating attendees.
If you would like to attend please send an e-mail to 
<script type="text/javascript"><!--
  var usr = "YSF.SystematicsAssociation";
  var dom = "gmail";
  var tld = "com";
  var ady = usr + "@" + dom + "." + tld;
  document.write("(<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>)")
  //--></script>, supplying your name and contact address.</p>
