<p style="background-color: #cc6633;">Reminder &amp; update:
Please <a href="#Registration">register</a> to attend the YSF by this <strong>Friday, 
22 November</strong>. We need your registration to arrange the catering, the security 
details, and to send you the final time schedule and abstracts.
<strong>New this year</strong> - registered participants will be welcomed to a light 
sandwich lunch at the event, and the usual stimulating post-symposium wine reception.</p>
