<P class="title">Forthcoming Publication</P>
		 <div class="textsmall">
<img src="/publications/covers/v83.png" width="150" height="197" 
alt="Early Events in Monocot Evolution, volume 83" 
title="Early Events in Monocot Evolution, volume 83" />
<p>ISBN 9781107012769; available from May 2013</p>
<p><a href="http://www.cambridge.org/gb/knowledge/isbn/item7141966/" rel="external">Available in Hardback</a> from CUP</p> 
     </div>