<P class="title">Latest Publication</P>
		 <div class="textsmall">
<a href="/publications/"><img src="/publications/covers/9781107028586-small.jpg" width="150" height="196"
alt="Next Generation Systematics"
title="Next Generation Systematics"
style="border: none;" /></a>
<p>Hardback (ISBN-13: 9781107028586)<br>Publication date: May 2016</p>
<p><a href="http://www.cambridge.org/gb/academic/subjects/life-sciences/evolutionary-biology/next-generation-systematics?format=HB" rel="external">Available in Hardback</a> from CUP</p>
     </div>