<P class="title">Latest Publication</P>
		 <div class="textsmall">
<a href="/publications/"><img src="/publications/covers/v84.png" width="150" height="197" 
alt="Descriptive Taxonomy - The Foundation of Biodiversity Research, volume 84" 
title="Descriptive Taxonomy - The Foundation of Biodiversity Research, volume 84" 
style="border: none;" /></a>
<p>ISBN 9780521761079;<br>published January 2015</p>
<p><a href="http://www.cambridge.org/gb/academic/subjects/life-sciences/ecology-and-conservation/descriptive-taxonomy-foundation-biodiversity-research" rel="external">Available in Hardback</a> from CUP</p> 
     </div>