<div style="border: groove green;padding: 10px 40px 40px 15px;"><P class="title">Member benefit</P>
		 <div class="textsmall">
The <strong>25% SA members' discount</strong> on SA published volumes is claimed 
by using a promotion code, for details of this code please contact David Gower
(<script type="text/javascript"><!--
  var usr = "d.gower";
  var dom = "nhm.ac";
  var tld = "uk";
  var ady = usr + "@" + dom + "." + tld;
  document.write("<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>")
//--></script>)
		 </div></div>
