Alex is a plant taxonomist at the Natural History Museum in London where his research aims 
to generate and document biological diversity data and to use this knowledge to 
establish and test hypotheses of relationships. In doing so to help meet civil society's 
demands of a global taxonomic resource as articulated in the Convention on Biological 
Diversity, its work programme and cross-cutting issues. Foci for this are the plant 
family Urticaceae and the Neotropics.

Links to online CV: <a href="http://www.nhm.ac.uk/research-curation/staff-directory/botany/a-monro/index.html" rel="external">Read CV</a>

Link to blog: <a href="http://tropicalbotany.wordpress.com" rel="external">Read Blog</a>
