Alex is a plant taxonomist at the Royal Botanic Gardens, Kew.
His research aims to generate and document biological diversity
data and collections and to use these to establish
and test hypotheses of relationships between taxa or areas.
In doing so, he aims to help meet civil society's demands
on taxonomy as articulated in the Convention on Biological
Diversity, its work programme and cross-cutting issues.
Foci for this are the plant family Urticaceae (nettles),
the Neotropics, karst and SW China.

Links to online CV: <a href="http://www.nhm.ac.uk/research-curation/staff-directory/botany/a-monro/index.html" rel="external">Read CV</a>

Link to blog: <a href="http://tropicalbotany.wordpress.com" rel="external">Read Blog</a>
