Alfried is Professor of Molecular Systematics at Imperial College London and has a 
joint appointment with the Natural History Museum.  His research interests are the 
molecular phylogenetics and evolutionary diversity of insects, in particular beetles 
(Coleoptera).  He is developing new methods in DNA taxonomy, large-scale phylogenetics 
and phylogenomics of insects.  He is co-director of two Masters courses at Imperial 
College/NHM (MRes Biosystematics and MSc Taxonomy and Biodiversity).
