Bryn is the Head of Mycology at the Royal Botanic Gardens, Kew where he studies 
molecular systematics of mushrooms and allies, as well as coevolution of fungi with 
plants and animals. He uses molecular tools and phylogenetic methods to document, 
diagnose, and compare fungi from all over the world, and has focused his fieldwork 
primarily in the tropics. He has taxonomic expertise in porcini mushrooms (Boletus) 
as well as the hairlike tropical coral mushroom family Pterulaceae, two species of 
which are cultivated by fungus-farming ants. His research interests are broad and 
range from documenting baseline fungal diversity to understanding evolutionary consequences 
of mushroom-mimicry by Dracula orchids.
