Beverley is Professor of Plant Systematics and Evolution, and Director of the Cambridge 
University Botanic Garden. Her area of interest is the evolution and development 
of floral traits that are important in attracting animal pollinators. By understanding 
how plants build traits that attract particular animals she aims to understand the 
diversification of the flowering plants. She uses a combination of molecular genetic, 
systematic and developmental techniques to address these problems.