Bente Klitg&aring;rd has a broad botanical background, is trained in most botanical technical 
skills and methods and has more than 25 years experience in multidisciplinary botanical 
research, science communication, and herbarium management and curation.  Her taxonomic 
research projects are largely focussed on the Legume (Leguminosae/Fabaceae) and Mint 
families (Lamiaceae) and span: field botany, collections-based taxonomy, and molecular 
and morphological phylogenetics. She also has a keen interest in the application 
of micro-morphological characters to solve systematic questions. In this field projects 
have included palynology, and floral development and evolution.

Link to CV -  <a href="http://www.kew.org/science-research-data/directory/people/Klitgaard_Bente.htm" rel="external">further information</a>
