Colin holds a Royal Society University Research Fellowship in systematic botany. 
His research interests are in taxonomic monography and phylogenetics of plant species. 
He is particularly interested in species-level problems, including species delimitation 
and classification, species-level phylogenetics, interspecific hybridization, geographical 
patterns of species diversification and species radiations, and early domestication 
of crop plants. He works mainly on Neotropical legumes, with current projects on the 
genera <em>Leucaena</em>, <em>Lupinus</em> and <em>Mimosa</em>.
