David has positions in the Universidad Complutense de 
Madrid and the Natural History Museum in London, is a former President of the International 
Union of Biological Sciences (IUBS), an Honorary President of the International Mycological 
Association (IMA), and was the last Director of the former International Mycological 
Institute (1983-97). He is currently Chair of the IUBS/IUMS International Committee 
on Bionomenclature (ICB), and Editor-in-Chief of <em>Biodiversity and Conservation</em>. His 
research focuses on the systematics of fungi (including lichens) using traditional 
and molecular phylogenetic approaches. Also known for studies on the bioindication 
of air quality and the use of fungi in the forensic investigation of serious crime, 
he has introduced over 800 new scientific names, including 74 genera new to science. 
He served the Systematics Association as Treasurer (1972-81) and Editor-in-Chief 
(1981-84, 1986), and is the editor or co-editor of eight volumes in the Association's 
Special Volumes series. His latest book, <em>Terms Used in Bionomenclature; the naming 
of organisms (and plant communities)</em> (2010) can be downloaded free of charge and 
interrogated through the Global Biodiversity Information Facility (GBIF) website.
