Diana works at the Natural History Museum, London as a Research Entomologist. Her research
focuses on species diversity and the evolutionary patterns and processes involved 
in insect-plant interactions. Her main taxon group of interest is the parasitic 
sap-feeding psyllids (Psylloidea, Hemiptera). She is interested in the dynamics 
of species interactions, and the radiation and patterns of plant and insect diversity 
on islands. She uses systematics and phylogenetic frameworks to understand the temporal 
and spatial components from both the plant and insect perspective. 
