Davide is a zoologist mostly interested in the use of large scale data sets (particularly 
genomic scale data sets) in phylogenetics.  My major research interest is in the 
study of invertebrate (particularly ecdysozoan) phylogenetics. Other research interests 
include the development of phylogenetic methods (particularly to recover large phylogenetic 
trees and to address difficult phylogenetic problems), and microbial phylogenetics.
