Dave is a microbiologist who has worked on ciliate systematics, eukaryotes in extreme 
environments, general eukaryotic relationships and environmental sampling using molecular 
methods.  Current research interests are focussed on environmental profiling, especially 
the detection of rare clones in environmental libraries and the general problem of 
discriminating species in microbes.  The other major component of Dave's working life 
is the EU EDIT project, in which he leads Workpackage 6 (Unifying Revisionary Taxonomy).  
See <a href="http://www.editwebrevisions.info/" rel="external">www.editwebrevisions.info</a> and 
<a href="http://www.nhm.ac.uk/research-curation/projects/euk-extreme/" rel="external">www.nhm.ac.uk/research-curation/<br>projects/euk-extreme/</a>
