Eve studies the taxonomy, systematics, biogeography and conservation of the guava 
family (Myrtaceae), with a focus on the predominantly Neotropical tribe Myrteae 
and the genus <em>Myrcia</em> s.l. She has interests also in Neotropical ecology and other 
Myrtaceae with fleshy fruits. 

Eve curates the Myrtales collection in the Kew herbarium, sits on the editorial 
boards of the Flora of the Guianas and Kew Bulletin and is an editor of Phytotaxa. 
Eve lectures on the Kew tropical id course and likes nothing more than Neotropical 
field work.
