Gemma works in the Herbarium, Library, Art &amp; Archives directorate at the Royal Botanic 
Gardens, Kew. She manages the curation of the Lamiaceae (Mint family) and Gesneriaceae 
(African Violet family), on which her research is focused. Gemma is currently revising 
the genus <em>Callicarpa</em> for the Flora Malesiana project, which aims to document and 
describe the flora of Indonesia, Malaysia, the Philippines, Papua New Guinea, Singapore 
and Brunei Darussalam. She is also interested in the systematics of the Lamiaceae 
in general, and worked with others to produce an Interactive Key to the family (<a href="http://www.kew.org/herbarium/keys/lamiales/">link</a>). 
Another group of interest is <em>Cyrtandra</em> (Gesneriaceae): Gemma is involved in collaborative 
research with the Gesneriaceae research group at the Royal Botanic Garden Edinburgh, 
and the Marie Selby Botanic Garden, Florida. She also co-organises the annual RBG Kew 
Tropical Plant Identification course with Dr Tim Utteridge.  In recognition of the 
need for scientists to take a more active role in public engagement with science, 
Gemma is a STEMNET ambassador and is involved in science communication at Kew.

