Greg is a Merit Researcher at the Natural History Museum (London), where 
he has worked since 2007. Previously he was Principal Research Scientist at the 
Australian Museum in Sydney, where he was employed from 1993 to 2007. His research 
involves the deep evolutionary relationships of arthropods, the pattern and timing 
of animal diversification during the Cambrian explosion, morphology and systematics 
of Palaeozoic arthropods known from exceptional preservation, and the systematics 
of centipedes (Chilopoda), drawing on integration of anatomical and molecular datasets.