Julie has been teaching and researching at the University of Reading since 1998. Principally 
interested in the systematics of flowering plants, particularly Fabales, and in systematic 
theory, she has published across abroad range of systematic areas - from homology assessment 
to the evolution of floras. More recently she has developed a research programme which 
exploits molecular marker data to determine identity, parentage and provenance of economically 
important plants in trade.
