Jon is currently a member of the biology department at St. Paul's School, London 
(<a href="http://www.stpaulsschool.org.uk/" rel="external">www.stpaulsschool.org.uk</a>). 
Before moving into teaching he worked as a post-doc on various research projects 
including  a worldwide monograph of the large genus <em>Solanum</em> (<a href="http://www.nhm.ac.uk/solanaceaesource/">www.nhm.ac.uk/solanaceaesource</a>) 
at the Natural History Museum, London and an investigation of the evolution of photoreceptors 
in the parasitic plant family Orobanchaceae in the lab of Dr Sarah Mathews, Harvard University. 
His interest in the systematics of the Lamiales began during his PhD studies on the 
taxonomy of <em>Strobilanthes</em> (Acanthaceae) in Oxford; Jon still retains an 
interest in the taxonomy of Acanthaceae.


