Juliet Brodie is a research phycologist at the Natural History Museum, London, specializing 
in the taxonomy, phylogeny, ecology, biodiversity and conservation of seaweeds.  
She studied red seaweeds for her PhD, supervised by Prof. Michael Guiry, Galway, 
Ireland, where she holds an adjunct Professorship. She is a specialist in the taxonomy 
and phylogeny of the <em>Porphyra</em>, red seaweed eaten around the world (e.g. laver bread 
in Wales and nori - the wrapping in sushi).  She also has an interest in the green 
algae, particularly endophytic species which occur in red and brown algae.  Juliet 
is keen to find ways of helping people to identify these organisms raise awareness 
of the seaweeds and their importance in coastal ecosystems, e.g. The Big Seaweed 
Search (<a href="http://www.nhm.ac.uk/nature-online/british-natural-history/seaweeds-survey/index.html" rel="external">http://www.nhm.ac.uk/nature-online/british-natural-history/seaweeds-survey/index.html</a>) 
which you can join in.
