Julia Day is a lecturer in the Department of Genetics, Evolution and the Environment, 
University College London. Her research focuses on the diversification of recent 
vertebrate radiations, principally from island-like settings. Much of her work to 
date is on fish groups from a biodiversity hotspot, Lake Tanganyika, with current 
projects focusing on the systematics and evolutionary history of Seychelles amphibians 
and montane East African birds.
