James' primary interests are in the use of dated molecular phylogenies to reconstruct 
the history of tropical plant taxa. His research integrates the disciplines of phylogenetics, 
taxonomy, palaeobotany, geology and palaeoclimatology. He has also used similar approaches 
to investigate the age of elements of the South African Cape flora. He will also be 
using molecular and morphological data to determine generic limits in Sapotaceae, leading 
to detailed monographic studies. Other current studies focus on <em>Inga</em> (Leguminosae), and 
previous work has been undertaken on Annonaceae and Rhamnaceae.
