Jon is a mollusc taxonomist focusing on fossil and living gastropods. His major 
research interests lie in integrating data from living and extinct taxa to; 1) study 
the systematic relationships and patterns of diversification of species-rich clades, 
particularly turrid and cerithioid snails, and 2) study diversity and macroecological 
change in marine molluscan communities in the Cenozoic and their relationship to 
key episodes of environmental change.  His focal regions include the Caribbean and 
the inland seas of the East African Rift. He is part of the Marie Curie Initial 
Training Network 'Throughflow' project (<a href="http://ipaeg.org/" rel="external">http://ipaeg.org/</a>) examining the historical 
development of the Southeast Asian marine biodiversity hotspot. Jon is curator of 
the collection of fossil benthic molluscs in the Natural History Museum, London. 
He is an organiser of the annual <a href="/ysf/">Young Systematists' Forum</a>.
