Jeremy Young is an expert on coccolithophores, which are one of the main groups 
of planktonic algae and which have an enormous fossil record as a result of the 
calcareous plates, coccoliths they produce. He is a  geologist and palaeontologist 
by training but his research has focussed mostly on living coccolithophores for 
the past few years. This has included participating in a series of research cruises 
as part of the <a href="http://www.surfaceoa.org.uk/" rel="external">UK Ocean Acidification Programme</a>. His systematics interests include 
web-delivery of taxonomy, and integration of biological and palaeontological data. 
He is currently Research Associate at University College London.<br>
Links to: <a href="http://nannotax.org/" rel="external">Nannotax website</a>, 
<a href="http://ina.tmsoc.org/" rel="external">International Nannoplankton Association</a>, 
<a href="http://www.surfaceoa.org.uk/" rel="external">UKOA surface consortium</a>,
blogs: <a href="http://www.antarcticoacruise.org.uk/" rel="external">antarcticoacruise.org.uk</a>, 
<a href="http://www.arcticoacruise.org/" rel="external">www.arcticoacruise.org</a>.
