Lauren is a botanist in the Herbarium at the Royal Botanic Gardens, Kew, 
specialising in palms and orchids. She completed her PhD at the University of East 
Anglia in association with Kew on the phylogenetics of the genus <em>Vanda</em> (Orchidaceae) 
and the MSc degree in Plant Taxonomy and Evolution at Reading University. Her current 
research at Kew is focussed on the systematic of the palm genus <em>Heterospathe</em> in 
New Guinea, conservation and population genetics of Madagascan palms, and developing 
the online eTaxonomy portal Palmweb (<a href="http://www.palmweb.org" rel="external">www.palmweb.org</a>). In her own time she is working 
towards the monograph of the genus <em>Vanda</em> with a number of collaborators, and acts 
as consultant to the Writhlington School Orchid Project (<a href="http://www.wsbeorchids.org" rel="external">www.wsbeorchids.org</a>) and 
their network of international orchid conservation projects.
