My main research interests are centered on floral morphology, the evolution of flowers 
and the use of floral characters in plant phylogeny. The great changes in the phylogeny 
based on molecular data represent an exciting field to revisit morphology in a new 
framework of plant affinities and to link morphological studies with other research 
areas, such as evolutionary developmental genetics (evo-devo) and ecology. I am 
specialized in the study of floral development and anatomy, which can be increasingly 
used as support for the molecular phylogeny in understanding the homology of characters 
for phylogenetic analyses and in the understanding of the underlying genetics of 
character expression.
See also <a href="http://www.rbge.org.uk/science/tropical-diversity/louis-ronse-de-craene" rel="external">research profile</a> 
