Marcello's research interest cover primitive limbed vertebrates (tetrapods), especially 
Devonian to Permian groups, and Palaeozoic echinoderms (with emphasis on the chordate-like 
and problematic stylophorans). Major research themes include inter-relationships of 
major groups of Palaeozoic tetrapods, the assembly of characters along the stem-groups 
of amphibians and amniotes, the use of morphometrics to evaluate disparity, rates 
of character change, palaeobiogeography and the study of variance in selected morphofunctional 
systems (e.g. appendicular skeleton, lower jaw). He is currently a postdoctoral researcher 
involved in phylogenetic aspects of the Permo-Triassic mass extinction.
