Maria is a plant taxonomist specialising in grasses, researching the diversity and 
evolutionary history of Madagascar grasslands and their species of Poaceae. She 
looks after the Poaceae herbarium collection at Kew Gardens and maintains Grassbase, 
a database of names and descriptions of all the world's grass species: <a href="http://www.kew.org/data/grasses-db.html" rel="external">http://www.kew.org/data/grasses-db.html</a>. 
Maria also teaches courses on grass identification, she is an Editor of the journal 
Phytotaxa and a Book Reviews Editor for the Botanical Journal of the Linnean Society, 
and an organiser of the annual <a href="/ysf/">Young Systematists Forum</a>.
