Matthew Wills is a palaeobiologist interested in the relationships of arthropods, 
and in the ways in which fossils can help to shed light on deep phylogenetic questions 
more generally. He also works on quantifying macroevolutionary trends, on the manner 
in which major clades explore 'design space', and on measuring the stratigraphic 
congruence of cladograms. He is currently Reader in Evolutionary Biology at the 
University of Bath.  Links to: 
<a href="http://www.bath.ac.uk/bio-sci/biodiversity-lab/?page_id=39" rel="external">Lab profile</a> and 
<a href="http://www.bath.ac.uk/bio-sci/contacts/academics/matthew_wills/" rel="external">Department profile</a>
