Olwen is a researcher at the Royal Botanic Gardens, Kew, where her research programme 
focuses on the evolution and diversity of succulent plants and desert floras. Olwen 
is interested in the use of plant systematics to enhance decision making around 
priorities for research or conservation attention, and emerging tools for phylogenetic 
prediction. She has a particular interest in the iconic African genus <em>Aloe</em> 
(Xanthorrhoeaceae).