Peter's research interests are in the patterns and processes of animal diversity. 
His group focuses on the parasitic flatworms (Platyhelminthes), combining studies 
in phylogenetics, development and genomics to address the mechanistic and evolutionary 
basis of their form and complex life histories. For more information please visit 
<a href="http://www.olsonlab.com/" rel="external">www.olsonlab.com</a>