Pablo is a botanist working on the systematics of tropical plants.
He is currently studying a group of species within the family Convolvulaceae,
and has previously worked on the systematics of Euphorbiaceae in South America.
He also has an interest in biodiversity conservation and in data management and
the promotion of open access in science, and has worked in several projects in
connection with GBIF and the Convention on Biological Diversity
