Peter's main research interest is the tropical trees of South East Asia. He is particularly 
interested in the families Sapotaceae and Malvaceae (subfamily Sterculioideae) and 
is currently focused on producing monographs of species rich genera in the Sapotaceae 
and on producing regional floras in Malaysia. A key aspect of his research is the 
production of molecular data to provide robust phylogenies of Sapotaceae to aid 
generic delimitation and support monographic research. Peter is currently developing 
the <a href="http://www.rbge.org.uk/science/tropical-diversity/Monographic-phylogenetic-research/sapotaceae">
Sapotaceae Resource Centre</a> which provides access to important data for monographic 
studies. This will help connect Sapotaceae researchers from around the world and 
provide a valuable research tool for monographers from countries that are species 
rich but resource poor.
