After gaining his first degree in Botany from the University of Reading, Rupert remained 
in the Herbarium of the School of Plant Sciences for 13 years, where he developed 
his database skills, putting the Herbarium online. In 2001, he moved to the Royal 
Horticultural Society Garden at Wisley, where he took over running the RHS Horticultural 
Database, expanding his role in 2005 to cover management of all horticultural data 
within the Science at the RHS. Rupert maintains a keen interest 
in evolving technologies and their possible applications in botany and horticulture.
