Richard's research interests are integrating morphological (including palaeobotanical) 
and molecular data to study major transitions in land-plant evolution at all spatial 
scales. His favourite study groups are living orchids and fossil clubmosses and gymnosperms, 
and his pet evolutionary hypothesis is the potential for instant, radical shifts 
in phenotype (i.e. saltation). He is currently Vice-President of both the Linnean 
Society and the Botanical Society of the British Isles, President of the UK Hardy 
Orchid Society, and part-time Head of Policy at the Biosciences Federation. He also 
holds a Visiting Professorship at Reading University.
