After gaining his BSc in Biology from Imperial College London, Ross then went on 
to the Natural History Museum 'Advanced Methods in Taxonomy &amp; Biodiversity' MSc 
course, where he gained a fine appreciation for cladistics. He completed his PhD 
thesis at the University of Bath investigating the importance of fossils in phylogeny.
Ross takes a keen interest in communicating science via social media, as well as 
the Panton Principles for Open Data in Science with which he hopes to encourage 
everyone to share publication data more openly and in a more reusable way. <a href="http://about.me/rossmounce" rel="external">http://about.me/rossmounce</a>