Robert Scotland is currently Reader in Systematic Botany in the Department of Plant 
Sciences at the University of Oxford and President-elect of the SA.  He has had 
several stints on the SA council and was Botanical Secretary of the SA when a PhD  
student.  He has broad taxonomic interests in Acanthaceae, systematic theory with 
a recent focus on the process of species discovery with a view to accelarating 
the pace of taxonomy through 'Foundation Monographs'. As an undergraduate he studied 
under Margaret Collinson at Kings, London and his PhD from the NHM London was supervised 
by Chris Humphries and Stephen Blackmore. He has supervised 10 PhD students and 
for the last fifteen years has run undergraduate field courses in Portugal and recently 
Tenerife.
