Rachel Walker is a postdoctorate researcher at the Natural History Museum, London. 
She completed a Masters degree at Imperial College in taxonomy and biodiversity, 
studying the systematics of coralline red algae, which she continues to work on. 
She first developed an interest in the Cape flora during her undergraduate degree 
and continued to study species from this region for her PhD at Cambridge University, 
on the evolution and development of petal spots in the South African daisy, <em>Gorteria 
diffusa</em>. She has recently returned to working on the red algae, to generate a taxonomic 
discovery system for macroalgal microbiomes using bioinformatic techniques. She 
is developing her research interests in projects that use a phylogenetic basis to 
study the evolution of novel traits and associations in plants and algae.
