Steven's research activities focus on xylem evolution and structure-functional relationships 
of wood. While various wood anatomical diversity patterns reflect their phylogenetic 
significance, some of the variation can be explained as a result of ecological and 
functional adaptations, especially with respect to conductive efficiency, vulnerability 
to embolism, and mechanical strength. He also studies the taxonomic variation of 
mineral elements in plants.
