Stefanie is a palaeobiologist working on the evolutionary history of sharks, skates 
and rays. She is particularly interested in their secret of success in past and 
present environments. Her approaches include systematic work as well as phylogenetic 
and biodiversity analyses, and calculations of the timing of specific adaptations 
(e.g. to the deep-sea).
Stefanie did her MSc in Munich (GER) and completed her PhD in Berlin (GER) before 
she became a Marie Curie Research Fellow at the University of Bristol in 2010 where 
she still is working in the Palaeobiology Research Group.
