Tiina is a tropical plant taxonomist based at the Royal Botanic Garden Edinburgh. 
Her research focuses on analysing species distribution patterns in South America, 
especially so in mega-diverse but poorly collected areas in the tropical Andes. 
Tiina is currently working on <a href="http://solanaceae.myspecies.info/" rel="extrnal">Solanaceae</a>, 
a plant family which contains many cultivated crops such as tomato, potato, eggplant, 
and chilli peppers. Her research aims to understand species diversity patterns within 
the family across the Neotropics. She also works on <em>ex situ</em> conservation of crop 
wild relative species through collaboration with the <a href="http://www.croptrust.org/" rel="external">Global Crop Diversity Trust</a>. 
