Tim is a botanist working in the South-East Asia regional team at the Royal Botanic 
Gardens, Kew. His work is primarily descriptive taxonomy on woody dicots, but is 
also a generalist botanist with particular interests in New Guinea and Borneo. He 
has undertaken research in several families from the Asian region, and has a current 
focus in the Icacinaceae, Stemonuraceae, and tropical Primulaceae. Tim is also co-organiser 
of Kew's annual Tropical Plant Identification course with Dr. Gemma Bramley.
