Vincent is Reader in Ecology &amp; Evolutionary Biology at Imperial College London 
and the Royal Botanic Gardens Kew. He coordinates the European Research Training network 
on 'understanding and conserving the earth's biodiversity hotspots' (HOTSPOTS), and 
several individual-driven EU Marie Curie postdoctoral projects on co-evolution, speciation, 
evolutionary radiations, biodiversity patterns and climate change. He leads two projects 
funded by the Darwin Initiative for the Survival of Species in Southern Africa and Central 
America. His additional research interests include: angiosperm phylogeny; Tree of Life; 
evolutionary processes and phylogenetic patterns; evolutionary rates; speciation; pollination 
biology and biological interactions; evolutionary developmental biology; DNA barcoding; conservation.
