Bill is head of palm research at Kew. His research interests range from the taxonomy 
of Old World palms to tackling broader evolutionary questions across the palm family. 
An active fieldworker, Bill is currently focusing on palms in the Asia-Pacific region, 
especially New Guinea and Lord Howe Island, and Madagascar. He is a Research Associate 
of Fairchild Tropical Botanic Garden in Miami, Florida, and also sits on committees 
in the Linnean Society and the Royal Horticultural Society.
