Wolfgang W&uuml;ster is a herpetologist with research interests in the systematics, biogeography 
and ecology of reptiles, particularly venomous snakes, and in the origin of venoms, 
the evolution of toxin families and the causes of variation in venom composition 
in snakes. He teaches widely in zoology, with emphases on evolutionary biology, 
systematics and herpetology, including field courses in the UK and overseas.
