Xavier is a plant biologist based at the Natural History Museum in London. His 
research interests are the taxonomy, phylogenetics and diversification of the spiny 
solanums (Solanaceae) of Tropical Asia. Xavier completed his PhD at Paris Natural 
History Museum in 2012 and where he became passionate about plants' evolution in 
the incredibly species rich island of Madagascar. He still working on the diversification 
of the mega-diverse genus <em>Euphorbia</em> (Euphorbiaceae) in Madagascar.
