Zofia is a world expert on the systematics and ecology of the fungal genera <em>Penicillium</em> 
and <em>Aspergillus</em>, and has a particular interest in their roles as food spoilage organisms. 
In this capacity she has, since 1987, acted as the United Kingdom representative on 
The International Commission for <em>Penicillium</em> and <em>Aspergillus</em> Systematics, and The 
International Working Committee for Stored Product Protection. She is a visiting 
lecturer at the University of Minho, Portugal and the Institute of Science and Food 
Protection (ISPA), Italy. Although retired, she still publishes and remains active 
in both her research field and the wider interests and promotion of systematics.
