<p>We recognise the following countries:</p>
<p><strong>Low-income economies</strong></p>
Afghanistan<br>
Bangladesh<br>
Benin<br>
Burkina Faso<br>
Burundi<br>
Cambodia<br>
Central African Republic<br>
Chad<br>
Comoros<br>
Congo, Dem. Rep<br>
Eritrea<br>
Ethiopia<br>
Gambia, The<br>
Ghana<br>
Guinea<br>
Guinea-Bissau<br>
Haiti<br>
Kenya<br>
Korea, Dem Rep.<br>
Kyrgyz Republic<br>
Lao PDR<br>
Liberia<br>
Madagascar<br>
Malawi<br>
Mali<br>
Mauritania<br>
Mozambique<br>
Myanmar<br>
Nepal<br>
Niger<br>
Rwanda<br>
Senegal<br>
Sierra Leone<br>
Somalia<br>
Tajikistan<br>
Togo<br>
Uganda<br>
Uzbekistan<br>
Vietnam<br>
Yemen, Rep.<br>
Zambia<br>
Zimbabwe<br>
<p><strong>Lower-middle-income economies</strong></p>
Albania<br>
Angola<br>
Armenia<br>
Azerbaijan<br>
Belize<br>
Bhutan<br>
Bolivia<br>
Cameroon<br>
Cape Verde<br>
China<br>
Congo, Rep.<br>
C&ocaret;te d'Ivoire<br>
Djibouti<br>
Ecuador<br>
Egypt, Arab Rep.<br>
El Salvador<br>
Georgia<br>
Guatemala<br>
Guyana<br>
Honduras<br>
India<br>
Indonesia<br>
Iran, Islamic Rep.<br>
Iraq<br>
Jordan<br>
Kiribati<br>
Kosovo<br>
Lesotho<br>
Maldives<br>
Marshall Islands<br>
Micronesia, Fed.Sts.<br>
Moldova<br>
Mongolia<br>
Morocoo<br>
Nicaragua<br>
Nigeria<br>
Pakistan<br>
Papua New Guinea<br>
Paraguay<br>
Philippines<br>
Samoa<br>
Sao Tome and Principe<br>
Solomon Islands<br>
Sri Lanka<br>
Sudan<br>
Swaziland<br>
Syrian Arab Republic<br>
Thailand<br>
Timor-Leste<br>
Tonga<br>
Tunisia<br>
Turkmenistan<br>
Ukraine<br>
Vanuatu<br>
West Bank and Gaza<br>
<p><strong>Upper-middle-income economies</strong></p>
Algeria<br>
American Samoa<br>
Argentina<br>
Belarus<br>
Bosnia and Herzegovina<br>
Botswana<br>
Brazil<br>
Grenada<br>
Jamaica<br>
Kazakhstan<br>
Latvia<br>
Lebanon<br>
Libya<br>
Lithuania<br>
Bulgaria<br>
Chile<br>
Colombia<br>
Costa Rica<br>
Cuba<br>
Dominica<br>
Dominican Republic<br>
Fiji<br>
Gabon<br>
Grenada<br>
Jamaica<br>
Kazakhstan<br>
Latvia<br>
Lebanon<br>
Libya<br>
Lithuania<br>
Macedonia, FYR<br>
Malaysia<br>
Mauritius<br>
Mayotte<br>
Mexico<br>
Montenegro<br>
Namibia<br>
Palau<br>
Panama<br>
Peru<br>
Poland<br>
Romania<br>
Russian Federation<br>
Serbia<br>
Seychelles<br>
South Africa<br>
St. Kitts and Nevis<br>
St. Lucia<br>
St. Vincent and the Grenadines<br>
Suriname<br>
Turkey<br>
Uruguay<br>
Venezuela, RB<br>
<p>As identified by the World Bank</p>