				<img src="../images/SystAssLogo-75.png" width="242"
        height="306" alt="Systematics Association" title=
        "Systematics Association" style=
        "float: right; margin-left: 5px;">
  <embed 
	  src="/ir/imagerotator.swf" 
	  width="205" 
	  height="306"
	  allowscriptaccess="always" 
	  allowfullscreen="true" 
	  flashvars="file=/ir/celebrate75.xml&transition=blocks&showicons=false&shownavigation=false&shuffle=true&overstretch=none&kenburns=true&usefullscreen=false&screencolor=0x808080&backcolor=0x808080" 
	/>

				
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
