<p style="background-color: #cc6633;">The deadline for the submission of Abstracts 
for talks has been extended to <strong>19 June 2011</strong>.</p>

<p>Please complete an <a href="/biennial2011/SA_2011_biennial_abstract_form_v2.doc">
abstract form</a> if you wish to present a poster or an oral presentation.</p>  

<p>Please note that we will accommodate as many talks as possible but if we are unable 
to do so then we will offer you the option of presenting a poster.</p>

<p>On the form you can indicate if you wish your talk to be considered for inclusion 
in one of the four thematic symposium:</p>

<ul>
<li>Next Generation Systematics - studying evolution and diversity in an era of ubiquitous genomics</li>
<li>Arthropod Systematics: are morphology, palaeontology and molecules coming together?</li>
<li>Algal Systematics: where next?</li>
<li>Advances in using museum specimens and ancient DNA in systematics research</li>
</ul>

<p><a href="/biennial2011/SA_2011_biennial_abstract_form_v2.doc">Download</a> a copy of the abstract form.</p>

<p style="background-color: #cc6633;"><strong>Please email your completed form as a word document to <script type="text/javascript"><!--
  var usr = "systass";
  var dom = "qub.ac";
  var tld = "uk";
  var ady = usr + "@" + dom + "." + tld;
  document.write("<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>")
//--></script> by 19th June 2011</strong></p>
