<p>To book accommodation for the conference we recommend that you use the official 
online booking site provided for us by the Belfast Visitor &amp; Convention Bureau.</p>

<p class="title"><a href="https://www.conferencebookings.co.uk/delegate/BLFSYMA2011" rel="external">Visit official conference accommodation site.</a>

<p>Accommodation is available ONLINE until 22nd May 2011 at the negotiated conference 
rates (from &pound;32 per person per night inclusive of Bed + Breakfast.</p>

<p>The conference will be held in the Medical Biology Centre, shown on Google map 
as the Lisburn Road side of Belfast City Hospital complex.</p>

