<ul>
<li><a href="http://www.qub.ac.uk/" rel="external">Queen's University, Belfast</a></li>
<li><a href="http://www.qub.ac.uk/schools/SchoolofBiologicalSciences/" rel="external">School of Biological Sciences, Queen's University</a></li>
<li><a href="https://admin.qol.qub.ac.uk/ecommerce/biocom/index.php" rel="external">Official Conference Registration site</a></li>
<li><a href="https://www.conferencebookings.co.uk/delegate/BLFSYMA2011" rel="external">Belfast Visitor &amp; Convention Bureau (official conference accommodation site)</a></li>
</ul>		
