<ul>
<li class="compact">Juliet Brodie (President of the Systematics Association)</li>
<li class="compact">Pete Olson (Treasurer of the Systematics Association)</li>
<li class="compact">James Cotton (Programme Secrtary of the Systematics Association)</li>
</ul>

<p><strong>Local organising committee:</strong></p>
<ul>
<li class="compact">Christine Maggs<br> (School of Biological Sciences, Queen's University Belfast)
<br><script type="text/javascript"><!--
  var usr = "systass";
  var dom = "qub.ac";
  var tld = "uk";
  var ady = usr + "@" + dom + "." + tld;
  document.write("<a href=\"" + "mai" + "lto:" + ady + "\">" + ady + "<" + "/a>")
//--></script></li>
<li class="compact">Julia Sigwart (School of Biological Sciences, QUB)</li>
<li class="compact">Fr&eacute;d&eacute;ric Mineur (School of Biological Sciences, QUB)</li>
<li class="compact">Christine Morrow (School of Biological Sciences, QUB)</li>
<li class="compact">John Bothwell (School of Biological Sciences, QUB)</li>
<li class="compact">Bernard Picton (Ulster Museum)</li>
</ul>
</p>