<p>Registration for the 2011 Biennial is now open. To register please follow the link 
below which will take you to a separate site.</p>

<p class="title">Go to <a href="https://admin.qol.qub.ac.uk/ecommerce/biocom/index.php" rel="external">Registration site</a> (opens in a new window)</p>

<p><strong>Registration rates:</strong>
<ul>
<li>Ordinary members &pound;180.00</li>
<li>Non-members &pound;195.00 (Why not <a href="/membership/">join the Systematics Association</a> and save money?)</li>
<li>Student members &pound;120.00</li>
</ul>

<ul>
<li>Members daily rate &pound;50.00</li>
<li>Non-Members daily rate &pound;75.00 (Why not <a href="/membership/">join the Systematics Association</a> and save money?)</li>
</ul>

<ul>
<li>Banquet &pound;40.00</li>
<li>Excursions from &pound;12.00 to &pound;35.00</li>
</ul>
</p>
