<!-- Close id=centerCol -->
</div>
<a name="Timetable"></a><p class="title">Timetable - <a style="text-decoration: none;color:#FFFF00;" href="SystAssBiennial2011_DetailedTimetable_v3 _2.pdf">download here</a></p>
<p style="clear:both; padding:1em 0; text-align:right; width:100%; font-size:90%;">Skip to <a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Monday">Monday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Tuesday">Tuesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Wednesday">Wednesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Thursday">Thursday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Friday">Friday</a></p>
<div id="centerColForm">
<p style="background-color: #cc6633"><strong>Please note that the timetable is subject to change</strong></p>
<table border="0" summary="" style="background-color: #ffffff;color: #000000;width:100%;">
<tr><th colspan="2" style="text-align: center;"><a name="Monday"></a>Monday 6th</th></tr>
<tr><th colspan="2"style="text-align: center;">Large Theatre</th></tr>
<tr><td>11:00-11:05</td><td style="padding-left: 10px;">Welcome to 8th biennial conference of the Systematics Association<br>Juliet Brodie</td></tr>
<tr><th colspan="2" style="background-color: #c2d69b;text-align: center;">SYMPOSIUM:<br>ALGAL SYSTEMATICS - WHERE NEXT?<br>Chair: Juliet Brodie</th></tr>
<tr><td>11:05-12:00</td><td style="background-color: #c2d69b;padding-left: 10px;">KEYNOTE<br>1. Exploring the amazing world of algae, from cultures to single cells<br>Debashish Bhattacharya</td></tr>
<tr><td>12:00-12:30</td><td style="background-color: #c2d69b;padding-left: 10px;">2. Horizontal gene transfer in algae<br>John A. Raven</td></tr>
<tr><td>12:30-14:00</td><td style="background-color: #948a54;text-align: center;">LUNCH</td></tr>
<tr><td>14:00-14:30</td><td style="background-color: #c2d69b;padding-left: 10px;">3. Genomic approaches to algal evolution: help or hindrance?<br>John Bothwell</td></tr>
<tr><td>14:30-15:00</td><td style="background-color: #c2d69b;padding-left: 10px;">4. The rappemonads and their sisters: new and diverse additions to the algal tree of life<br>Thomas A. Richards</td></tr>
<tr><td>15:00-15:30</td><td style="background-color: #c2d69b;padding-left: 10px;">5. Phylogeography of seaweeds: significance of cryptogenic species<br>Fr&eacute;d&eacute;ric Mineur</td></tr>
<tr><td>15:30-16:00</td><td style="background-color: #fabf8f;text-align: center;">COFFEE</td></tr>
<tr><td>16:00-16:30</td><td style="background-color: #c2d69b;padding-left: 10px;">6. Glacial survival and unique genetic lineages under threat from current global climate change<br>Jim Provan</td></tr>
<tr><th colspan="2" style="background-color: #b2a1c7;text-align: center;">CONTRIBUTED TALKS<br>Chair: Juliet Brodie</th></tr>
<tr><td>16:30-16:50</td><td style="background-color: #b2a1c7;padding-left: 10px;">7. Towards an understanding of phylogenomic relationships in the Bangiales (Rhodophyta)<br>Juliet Brodie</td></tr>
<tr><td>16:50-17:10</td><td style="background-color: #b2a1c7;padding-left: 10px;">8. New roles for systematics in next generation biology<br>David Patterson</td></tr>
<tr><td>17:30-19:00</td><td style="text-align: center;">WELCOME RECEPTION</td></tr>
</table>
</div>

<p style="clear:both; padding:1em 0; background:url(/images/topofpage.gif) no-repeat center right; text-align:right; width:100%; font-size:90%;">Skip to <a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Monday">Monday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Tuesday">Tuesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Wednesday">Wednesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Thursday">Thursday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Friday">Friday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#_top" title="Back to the top of the page">Top of page</a></p>

<div id="centerColForm">
<table border="0" summary="" style="background-color: #ffffff;color: #000000;width:100%;">
<tr><th colspan="2" style="text-align: center;"><a name="Tuesday"></a>Tuesday 5th</th></tr>
<tr><th colspan="2" style="text-align: center;">Large Theatre</th></tr>
<tr><th colspan="2" style="background-color: #d995c7;text-align: center;">SYMPOSIUM:<br>NEXT GENERATION SYSTEMATICS:<br>STUDYING EVOLUTION AND DIVERSITY IN AN ERA OF UBIQUITOUS GENOMICS<br>Chairs: James Cotton, Peter Olson, Joseph Hughes</th></tr>
<tr><td>9:00-9:30</td><td style="background-color: #d995c7;padding-left: 10px;">9. A genome-sequence tree for Nematoda based on hundreds of genomes<br>Mark Blaxter</td></tr>
<tr><td>09:30-10:00</td><td style="background-color: #d995c7;padding-left: 10px;">10. Using phylogenomics to resolve the fungal tree of life<br>David Fitzpatrick</td></tr>
<tr><td>10:00-10:30</td><td style="background-color: #d995c7;padding-left: 10px;">11. Pathogenomics: investigating bacterial microevolution through second generation genome sequencing<br>Simon Harris</td></tr>
<tr><td>10:30-11:00</td><td style="background-color: #fabf8f;text-align: center;">COFFEE</td></tr>
<tr><td>11:00-11:30</td><td style="background-color: #d995c7;padding-left: 10px;">12. Plant systematics in the age of genomics revisited<br>Dennis Stevenson</td></tr>
<tr><td>11:30-12:00</td><td style="background-color: #d995c7;padding-left: 10px;">13. Insights into flatworm evolution through comparative genomics<br>Magdalena Zarowiecki</td></tr>
<tr><td>12:00-12:30</td><td style="background-color: #d995c7;padding-left: 10px;">14. Ultimate barcoding - next generation sequencing meets high throughput mitogenomics<br>Peter Foster</td></tr>
<tr><td>12:30-14:00</td><td style="background-color: #948a54;text-align: center;">LUNCH</td></tr>
<tr><td>14:00-14:30</td><td style="background-color: #d995c7;padding-left: 10px;">15. Next-generation biodiversity analysis<br>Mehrdad Hajijbabei</td></tr>
<tr><td>14:30-15:00</td><td style="background-color: #d995c7;padding-left: 10px;">16. Ecological differentiation of eukaryotic microbial lineages using 454 sequencing<br>David Bass</td></tr>
<tr><td>15:00-15:30</td><td style="background-color: #d995c7;padding-left: 10px;">17. Analysing metagenomic data to estimate diversity<br>Chris Quince</td></tr>
<tr><td>15:30-16:00</td><td style="background-color: #fabf8f;text-align: center;">COFFEE</td></tr>
<tr><td>16:00-16:30</td><td style="background-color: #d995c7;padding-left: 10px;">18. Next generation sequencing in population genetics of gall wasps<br>Graham Stone</td></tr>
<tr><td>16:30-17:00</td><td style="background-color: #d995c7;padding-left: 10px;">19. Ongoing evolution in allopolyploid genomes examined using next-generation sequencing<br>Richard Buggs</td></tr>
<tr><td>17:00-18:00</td><td style="background-color: #d995c7;padding-left: 10px;">KEYNOTE<br>20. The role of NGS for integrative approaches of evo-devo and population genetics<br>Ralf Sommer</td></tr>
<tr><td>18:00-19:30</td><td style="text-align: center;">POSTERS AND DRINKS RECEPTION<br>(sponsored by Cambridge University Press)</td></tr>
</table>
</div>

<p style="clear:both; padding:1em 0; background:url(/images/topofpage.gif) no-repeat center right; text-align:right; width:100%; font-size:90%;">Skip to <a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Monday">Monday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Tuesday">Tuesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Wednesday">Wednesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Thursday">Thursday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Friday">Friday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#_top" title="Back to the top of the page">Top of page</a></p>

<div id="centerColForm">
<table border="0" summary="" style="background-color: #ffffff;color: #000000;width:100%;">
<tr><th colspan="3" style="text-align: center;"><a name="Wednesday"></a>Wednesday 6th</th></tr>
<tr><td>&nbsp;</td><th style="text-align: center;">Large Theatre</th><th style="text-align: center;">Small Theatre</th></tr>

<tr><td>9:00-10:00</td><td colspan="2" style="padding-left: 10px;">HOW-TO TALK<br>21. Clustal Omega and multiple sequence alignments<br>Des Higgins<br>Chair: James Cotton</td></tr>

<tr>
<td>&nbsp;</td><th style="background-color: #b2a1c7;text-align: center;">CONTRIBUTED TALKS - THEORY AND  METHODS FOR PALAEONTOLOGICAL DATA<br>Chair: Matthew Wills</th>
<th style="background-color: #b2a1c7;text-align: center;">CONTRIBUTED TALKS - PLANT SYSTEMATICS AND EVOLUTION<br>Chair: Nina R&oslash;nsted
</tr>

<tr><td>10:00-10:20</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">22. Stratigraphic congruence through geological time and across higher taxa: what factors explain the variation?<br>Anne O'Connor</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">24. Snowdrops and snowflakes - falling slowly into place<br>Nina R&oslash;nsted</td>
</tr>

<tr><td>10:20-10:40</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">23. Morphological disparity and clade shapes through time<br>Martin Hughes</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">25. Phylogenetic studies of the aloes (<em>Aloe</em> L., Xanthorrhoeaceae)<br>Olwen Grace</td>
</tr>

<tr><td>10:40-11:10</td><td colspan="2" style="background-color: #fabf8f;text-align: center;">COFFEE</td></tr>

<tr>
<td>&nbsp;</td><th style="background-color: #b2a1c7;text-align: center;">CONTRIBUTED TALKS - ANIMAL SYSTEMATICS AND EVOLUTION<br>Chair: Julia Day</th>
<th style="background-color: #b2a1c7;text-align: center;">CONTRIBUTED TALKS -  PLANT SYSTEMATICS AND EVOLUTION CONT.<br>Chair: Julien Massoni</th>
</tr>

<tr><td>11:10-11:30</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">26. Biogeography and diversification in Africa: a case study from a species rich catfish clade<br>Julia Day</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">30. Evolutionary history of a 10,000-species clade of angiosperms: reconstructing the phylogeny of magnoliids as a whole<br>Julien Massoni</td>
</tr>

<tr><td>11:30-11:50</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">27. Evolutionary ecology of Lake Tanganyika's Mastacembelid eels<br>Katherine Brown</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">31. Comparative transcriptomics and genomics: determining the regulators of petal spot development and the evolution of this specialised floral trait within the species complex <em>Gorteria diffusa</em><br>Rachel Walker</td>
</tr>

<tr><td>11:50-12:10</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">28. Distinguishing signal, noise and bias in early animal evolution: The difficult problem of the sponge phylogeny<br>Roberto Fueda</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">32. Testing the impact of calibration on molecular divergence times using a fossil-rich group: The case of <em>Nothofagus</em> (Fagales)<br>Herv&eacute; Sauquet</td>
</tr>

<tr><td>12:10-12:30</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">29. Reconciling morphological and molecular classifications: an investigation of Hemiasterellidae (Demospongiae, Porifera)<br>Christine Morrow</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">33. How to resolve conflict between taxonomy and phylogeny in basal living chitons (Mollusca: Ployplacophora)<br>Julia Sigwart</td>
</tr>

<tr><td>12:30-</td><td colspan="2" style="background-color: #948a54;text-align: center;">LUNCH<br>EXCURSIONS</td></tr>
</table>
</div>

<p style="clear:both; padding:1em 0; background:url(/images/topofpage.gif) no-repeat center right; text-align:right; width:100%; font-size:90%;">Skip to <a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Monday">Monday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Tuesday">Tuesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Wednesday">Wednesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Thursday">Thursday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Friday">Friday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#_top" title="Back to the top of the page">Top of page</a></p>


<div id="centerColForm">
<table border="0" summary="" style="background-color: #ffffff;color: #000000;width:100%;">
<tr><th colspan="2" style="text-align: center;"><a name="Thursday"></a>Thursday 7th</th></tr>
<tr><th colspan="2" style="text-align: center;">Large Theatre</th></tr>
<tr><th colspan="2" style="background-color: #95b3d7;text-align: center;">SYMPOSIUM:<br>ARTHROPOD SYSTEMATICS:<br>ARE MORPHOLOGY, PALAEONTOLOGY AND MOLECULES COMING TOGETHER?<br>Chairs: Davide Pisani, Omar Rota-Stabelli and Ronald Jenner</td></tr>
<tr><th colspan="2" style="background-color: #95b3d7;text-align: center;">SESSION 1: THE ARTHROPODS AND THEIR OUTGROUPS</th></tr>
<tr><td>9:00-9:45</td><td style="background-color: #95b3d7;padding-left: 10px;">KEYNOTE<br>34. What have we learned from 25 years of animal molecular systematics?<br>Max Telford</td></tr>
<tr><td>9:45-10:15</td><td style="background-color: #95b3d7;padding-left: 10px;">35. Neural characters and arthropod systematics<br>Angelika Stollewerk</td></tr>
<tr><td>10:15-10:30</td><td style="background-color: #95b3d7;padding-left: 10px;">36. MicroRNA and phylogenomics reveal velvet worms as the arthropod sister group<br>Lahcen Campbell</td></tr>
<tr><td>10:30-11:00</td><td style="background-color: #fabf8f;text-align: center;">COFFEE</td></tr>
<tr><th colspan="2" style="background-color: #95b3d7;text-align: center;">SESSION 2: THE ARTHROPODS AND THEIR OUTGROUPS CONTINUED</th></tr>
<tr><td>11:00-11:30</td><td style="background-color: #95b3d7;padding-left: 10px;">37. On the position of myriapods: insights from Onycophora (velvet worms)<br>Georg Mayer</td></tr>
<tr><td>11:30-12:00</td><td style="background-color: #95b3d7;padding-left: 10px;">38. Molecular arthropod phylogeny: Early relationships and divergence times<br>Thorsten Burmester</td></tr>
<tr><td>12:00-12:20</td><td style="background-color: #95b3d7;padding-left: 10px;">39. Ten years later: Phylogenetics utility and limitations of mitochondrial gene order<br>Dennis Lavrov</td></tr>
<tr><td>12:20-13:00</td><td style="background-color: #95b3d7;padding-left: 10px;">DISCUSSION<br>What is the outgroup to the arthropods? Is Mandibulata definitive?</td></tr>
<tr><td>13:00-14:00</td><td style="background-color: #948a54;text-align: center;">LUNCH</td></tr>
<tr><th colspan="2" style="background-color: #95b3d7;text-align: center;">SESSION 3: THE PANCRUSTACEA PROBLEM(S)</td></tr>
<tr><td>14:00-14:30</td><td style="background-color: #95b3d7;padding-left: 10px;">40. Sources of deep-level phylogenetic signal in 62 protein-coding nuclear genes from arthropods<br>Jerome Regier</td></tr>
<tr><td>14:30-15:00</td><td style="background-color: #95b3d7;padding-left: 10px;">41. Phylogenomic and evolutionary aspects of Pancrustacea and Remipedia -the hope and headache of "phylogenomics"<br>Bj&oumlaut;rn von Reumont</td></tr>
<tr><td>15:00-15:30</td><td style="background-color: #95b3d7;padding-left: 10px;">DISCUSSION<br>What is the outgroup to the hexapods?</td></tr>
<tr><td>15:30-16:00</td><td style="background-color: #fabf8f;text-align: center;">COFFEE</td></tr>
<tr><th colspan="2" style="background-color: #95b3d7;text-align: center;">SESSION 4: MOLECULES AND FOSSILS...</th></tr>
<tr><td>16:00-16:30</td><td style="background-color: #95b3d7;padding-left: 10px;">42. The Devil in the detail: modern morphological methods allow the confident placement of fossil arachnids as molecular calibration points<br>Jason Dunlop</td></tr>
<tr><td>16:30-17:00</td><td style="background-color: #95b3d7;padding-left: 10px;">43. Morphological cladistics and arthropod phylogeny<br>Greg Edgecombe</td></tr>
<tr><td>17:00-17:20</td><td style="background-color: #95b3d7;padding-left: 10px;">44. Are morphology-based cladograms of arthropods really less robust than those of vertebrates?<br>Matt Wills</td></tr>
<tr><td>17:20-18:00</td><td style="background-color: #95b3d7;padding-left: 10px;">DISCUSSION<br>Why is there a persistent gap in the arthropod, particularly myriapods, fossil record?</td></tr>
<tr><td>18:00-18:45</td><td style="background-color: #95b3d7;padding-left: 10px;">KEYNOTE<br>45. Vistas in arthropod evolution: throughout phylogeny, and beyond<br>Alessandro Minelli</td></tr>
<tr><td>19.30 for 20.00</td><td>CONFERENCE BANQUET<br>Belfast City Hall</td></tr>
</table>
</div>

<p style="clear:both; padding:1em 0; background:url(/images/topofpage.gif) no-repeat center right; text-align:right; width:100%; font-size:90%;">Skip to <a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Monday">Monday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Tuesday">Tuesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Wednesday">Wednesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Thursday">Thursday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Friday">Friday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#_top" title="Back to the top of the page">Top of page</a></p>

<div id="centerColForm">
<table border="0" summary="" style="background-color: #ffffff;color: #000000;width:100%;">
<tr><th colspan="3" style="text-align: center;"><a name="Friday"></a>Friday 8th</th></tr>
<tr><td>&nbsp;</td><th style="text-align: center;">Large Theatre</th><th style="text-align: center;">Small Theatre</th></tr>
<tr>
<td>&nbsp;</td><th style="background-color: #bfbfbf;text-align: center;">SYMPOSIUM:<br>ADVANCES IN USING MUSEUM SPECIMENS AND ANCIENT DNA IN SYSTEMATICS RESEARCH<br>Chairs: Patricia Lee and Samantha Mohun</th>
<th>&nbsp;</th>
</tr>	

<tr><td>9:00-9:30<td style="background-color: #bfbfbf;padding-left: 10px;">46. Extracting DNA from museum collections of dried eggshells<br>Patricia Lee</td><td>&nbsp;</td>	
<tr><td>9:30-10:00<td style="background-color: #bfbfbf;padding-left: 10px;">47. DNA damage repair and amplification from formalin fixed specimens<br>Samantha Mohun</td><td>&nbsp;</td>	
<tr><td>10:00-10:30<td style="background-color: #bfbfbf;padding-left: 10px;">48. Museum archaeobotanical collections as a source of biomolecular information for archaeogenetic analysis<br>Oliver Smith</td><td>&nbsp;</td>	
<tr><td>10:30-11:00</td><td colspan="2" style="background-color: #fabf8f;text-align: center;">COFFEE</td></tr>
<tr><td>11:00-11:30<td style="background-color: #bfbfbf;padding-left: 10px;">49. Postglacial recolonisation mode of North American <em>Amara alpina</em> (Carabidae: Coleoptera) using museum and ancient DNA<br>Peter Heintzmann</td><td>&nbsp;</td>	
<tr><td>11:30-12:00<td style="background-color: #bfbfbf;padding-left: 10px;">50. Developing museum molecular collections: "A global repository for schistosomiasis research<br>Fiona Allen</td><td>&nbsp;</td>	
<tr><td>12:00-12:30<td style="background-color: #bfbfbf;padding-left: 10px;">51. Biobanking at the NHM London<br>Jacqueline MacKenzie-Dodds</td><td>&nbsp;</td>	
<tr><td>12:30-14:00</td><td colspan="2" style="background-color: #948a54;text-align: center;">LUNCH</td></tr>

<tr>
<td>&nbsp;</td><th style="background-color: #b2a1c7;text-align: center;">CONTRIBUTED TALKS -ADVANCES IN USING MUSEUM SPECIMENS AND ANCIENT DNA IN SYSTEMATICS RESEARCH<br>Chair: Christoph Hahn</th>	
<th style="background-color: #b2a1c7;text-align: center;">CONTRIBUTED TALKS - THEORY AND METHODS OF PHYLOGENETICS<br>Chair: Mark Wilkinson</th>
</tr>

<tr><td>14:00-14:20</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">52. Museomics for ectoparasites recovered from historical fish collections - lessons from <em>Gyrodactylus</em><br>Christoph Hahn</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">56. Fast Supertree Construction<br>Mark Wilkinson</td>

<tr><td>14:20-14:40</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">53. The DNA Bank Network - A platform for open access to voucher referenced DNA samples and data worldwide<br>Gabriele Droege</td>	
<td style="background-color: #b2a1c7;padding-left: 10px;">57. Convergent evolution at the sequence level - batty and malarial examples<br>James Cotton</td>

<tr><td>14:40-15:00</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">54. Quantitative morphometric assessment of the disparity of Lake Tangayika's endemic gastropod fauna<br>Olivia Cheronet</td>	
<td style="background-color: #b2a1c7;padding-left: 10px;">58. Rocks, Soils and Breaks: A new method for discovering and identifying biotic breaks<br>Malte Ebach</td>

<tr><td>15:00-15:20</td>
<td style="background-color: #b2a1c7;padding-left: 10px;">55. Herbarium DNA: extraction optimization, damage assessment and use.<br>Freek Bakker</td>	
<td style="background-color: #b2a1c7;padding-left: 10px;">59. <em>Nullius in Calculo</em>: On the Explicitness and Reproducibility of Cladistic Analyses<br>Ross Mounce</td>

<tr><td colspan="2">15:20-15:30	CLOSING REMARKS AND PRIZE-GIVING<br>Juliet Brodie</td>
</table>
</div>
<p style="clear:both; padding:1em 0; text-align:right; width:100%; font-size:90%;">Skip to <a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Monday">Monday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Tuesday">Tuesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Wednesday">Wednesday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Thursday">Thursday</a><a style="margin:0 25px 0 0;text-decoration: none;color:#FFFF00;" href="#Friday">Friday</a></p>
<div id="centerCol">
<!-- Add HTML for main body of page -->
