<p style="background-color: #cc6633"><strong>Please note that this draft timetable is subject to change</strong></p>

<p><strong>Monday 4th</strong><br>
11am - Conference begins. Plenary Debashih Bhattacharya.<br>
12:00-5:30	Symposium - Algal Systematics: where next?<br>
			Parallel Contributed talk sessions<br>
5:30-7:00	Welcome Reception and Posters</p>

<p><strong>Tuesday 5th</strong><br>
9:00-10:00 	Plenary - Ralf Sommer.<br>
10:00-5:30	Symposium - Next Generation Systematics<br>
			Contributed talk sessions<br>
5:30-7:00	Poster session and wine reception (sponsored by Cambridge University Press)</p>

<p><strong>Wenesday 6th</strong><br>
9:00-12:30	Contributed talk sessions<br>
2:00-5:30	Excusions</p>

<p><strong>Thursday 7th</strong><br>
9:00-09:45	Plenary - Max Telford.<br>
09:45-5:30	Symposium - Arthropod Systematics: are Morphology, Palaeontology and Molecules Coming Together?<br>
			Contributed talk sessions<br>
Evening - 		Conference Banquet</p>

<p><strong>Friday 8th</strong><br>
9:00-12:30	Symposium - Advances in Using Museum Specimens and Ancient DNA in Systematics Research<br>
			Symposium - Arthropod Systematics: are Morphology, Palaeontology and Molecules Coming Together? - continues.<br>
14:00-15:30	Contributed talk sessions<br>
15:30-16:00	Closing ceremony, presentation of student prizes. End of Conference.
</p>