<p>The conference will be held in the Medical Biology Centre, shown on Google map as 
the Lisburn Road side of Belfast City Hospital complex.</p>
<div id="GoogleMap"
<!-- ++Begin Map Search Control Wizard Generated Code++ -->
  <!--
  // Created with a Google AJAX Search Wizard
  // http://code.google.com/apis/ajaxsearch/wizards.html
  -->

  <!--
  // The Following div element will end up holding the map search control.
  // You can place this anywhere on your page
  -->
  <div id="mapsearch">
    <span style="color:#676767;font-size:11px;margin:10px;padding:4px;">Loading...</span>
  </div>

  <!-- Maps Api, Ajax Search Api and Stylesheet
  // Note: If you are already using the Maps API then do not include it again
  //       If you are already using the AJAX Search API, then do not include it
  //       or its stylesheet again
  //
  // The Key Embedded in the following script tags is designed to work with
  // the following site:
  // http://www.systass.org/
  -->
  <script src="http://maps.google.com/maps?file=api&v=2&key=ABQIAAAALcnWoXOucwAMkb7GXuuJJRT0FVRJgXhejblEDaADn1SKIkiHBhTb2L5tHs9rzSsZW9PRS4WqHFAKfg"
    type="text/javascript"></script>
  <script src="http://www.google.com/uds/api?file=uds.js&v=1.0&source=uds-msw&key=ABQIAAAALcnWoXOucwAMkb7GXuuJJRT0FVRJgXhejblEDaADn1SKIkiHBhTb2L5tHs9rzSsZW9PRS4WqHFAKfg"
    type="text/javascript"></script>
  <style type="text/css">
    @import url("http://www.google.com/uds/css/gsearch.css");
  </style>

  <!-- Map Search Control and Stylesheet -->
  <script type="text/javascript">
    window._uds_msw_donotrepair = true;
  </script>
  <script src="http://www.google.com/uds/solutions/mapsearch/gsmapsearch.js?mode=new"
    type="text/javascript"></script>
  <style type="text/css">
    @import url("http://www.google.com/uds/solutions/mapsearch/gsmapsearch.css");
  </style>

  <style type="text/css">
    .gsmsc-mapDiv {
      height : 350px;
    }

    .gsmsc-idleMapDiv {
      height : 350px;
    }

    #mapsearch {
      width : 425px;
      margin: 10px;
      padding: 4px;
    }
  </style>
  <script type="text/javascript">
    function LoadMapSearchControl() {

      var options = {
            zoomControl : GSmapSearchControl.ZOOM_CONTROL_ENABLE_ALL,
            title : "Systass Biennial 2011",
            url : "http://www.systass.org/biennial2011/",
            idleMapZoom : GSmapSearchControl.ACTIVE_MAP_ZOOM,
            activeMapZoom : GSmapSearchControl.ACTIVE_MAP_ZOOM
            }

      new GSmapSearchControl(
            document.getElementById("mapsearch"),
            "Medical Biology Centre 97 Lisburn Road Belfast BT9 7BL Northern Ireland",
            options
            );

    }
    // arrange for this function to be called during body.onload
    // event processing
    GSearch.setOnLoadCallback(LoadMapSearchControl);
  </script>
<!-- ++End Map Search Control Wizard Generated Code++ -->
</div>
<p><a href="http://maps.google.co.uk/maps?f=q&source=s_q&hl=en&geocode=&q=BT9%2B7BL&aq=&sll=53.800651,-4.064941&sspn=18.828876,39.506836&ie=UTF8&hq=&hnear=Belfast,+County+Antrim+BT9+7BL,+United+Kingdom&ll=54.584946,-5.942531&spn=0.00899,0.01929&t=h&z=16&layer=c&cbll=54.585402,-5.941137&panoid=MPS2nR7GpKx0HjIxq8cLqg&cbp=12,323.31,,0,0" rel="external">View in Google Streetview</a></p>