<!-- Start WOWSlider.com BODY section id=wowslider-container1 -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<!-- <li><a href="http://www.linnean.org/rewildingdebate" target="_blank"><img src="/images/2013event1.jpg" alt="2013Event1" title="2013Event1" id="wows1_0"/></a>A debate between conservationists and rewilders</li> -->
<li><a href="http://www.systass.org/biennial1997/" target="_blank"><img src="/images/1stBiennial1997.png" alt="1st SA Biennial 1997" title="1st SA Biennial 1997" id="wows1_1"/></a>First Systematics Association Biennial 19-21 August 1997, Oxford</li>
<li><a href="http://www.systass.org/biennial1999/" target="_blank"><img src="/images/2ndBiennial1999.png" alt="2nd SA Biennial 1999" title="2nd SA Biennial 1999" id="wows1_2"/></a>Second Systematics Association Biennial 23-27 August 1999, Glasgow</li>
<li><a href="http://www.systass.org/biennial2001/" target="_blank"><img src="/images/3rdBiennial2001.png" alt="3rd SA Biennial 2001" title="3rd SA Biennial 2001" id="wows1_3"/></a>Third Systematics Association Biennial 3-7 September 2001, London</li>
<li><a href="http://www.systass.org/biennial2003/" target="_blank"><img src="/images/4thBiennial2003.png" alt="4th SA Biennial 2003" title="4th SA Biennial 2003" id="wows1_4"/></a>Fourth Systematics Association Biennial 18-22 August 2003, Ireland</li>
<li><a href="http://www.systass.org/biennial2005/" target="_blank"><img src="/images/5thBiennial2005.png" alt="5th SA Biennial 2005" title="5th SA Biennial 2005" id="wows1_5"/></a>Fifth Systematics Association Biennial 22-26 August 2005, Cardiff</li>
<li><a href="http://www.systass.org/biennial2007/" target="_blank"><img src="/images/6thBiennial2007.png" alt="6th SA Biennial 2007" title="6th SA Biennial 2007" id="wows1_6"/></a>Sixth Systematics Association Biennial 28-31 August 2007, Edinburgh</li>
<li><a href="http://www.systass.org/biennial2009/" target="_blank"><img src="/images/7thBiennial2009.png" alt="7th SA Biennial 2009" title="7th SA Biennial 2009" id="wows1_7"/></a>First BioSyst EU and Seventh Systematics Association Biennial 10-14 August 2009, Leiden</li>
<li><a href="http://www.systass.org/biennial2011/" target="_blank"><img src="/images/8thBiennial2011.png" alt="8th SA Biennial 2011" title="8th SA Biennial 2011" id="wows1_8"/></a>Eighth Systematics Association Biennial 4-8 July 2011 Belfast</li>
<li><a href="http://www.systass.org/biennial2013/" target="_blank"><img src="/images/9thBiennial2013.png" alt="9th SA Biennial 2013" title="9th SA Biennial 2013" id="wows1_9"/></a>Second BioSyst EU and Nineth Systematics Association Biennial 18-22 February 2013, Vienna</li>
<li><a href="http://www.systass.org/biennial2015/" target="_blank"><img src="/images/10thBiennial2015.png" alt="10th SA Biennial 2015" title="10th SA Biennial 2015" id="wows1_10"/></a>Tenth Systematics Association Biennial 26-28 August 2015, Oxford</li>
</ul></div>
<span class="wsl"><a href="http://wowslider.com">Ajax Slider</a> by WOWSlider.com v4.7</span>
	<a href="#" class="ws_frame"></a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="wow-engine/wowslider.js"></script>
	<script type="text/javascript" src="wow-engine/script.js"></script>
<!-- End WOWSlider.com BODY section -->
