 <!-- Start WOWSlider.com BODY section id=wowslider-container1 -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<!-- <li><a href="http://www.linnean.org/rewildingdebate" target="_blank"><img src="/images/2013event1.jpg" alt="2013Event1" title="2013Event1" id="wows1_0"/></a>A debate between conservationists and rewilders</li> -->
<li><a href="http://www.linnean.org/Meetings-and-Events/Events/Willi+Hennig+and+the+Future+of+Phylogenetic+Systematics" target="_blank"><img src="/images/2013event2.jpg" alt="2013Event2" title="2013Event2" id="wows1_1"/></a>Willi Hennig (1913-1976): His Life, Legacy and the Future of Phylogenetic Systematics</li>
<li><a href="http://www.systass.org/events/Presidents_Lecture_2013.shtml"><img src="/images/2013event3.jpg" alt="2013Event3" title="2013Event3" id="wows1_2"/></a>John Wood - Plant Hunting in the 21st century</li>
<li><a href="http://www.systass.org/ysf/"><img src="/images/2013event4.jpg" alt="2013Event4" title="2013Event4" id="wows1_3"/></a>The annual Young Systematists' Forum</li>
</ul></div>
<span class="wsl"><a href="http://wowslider.com">Ajax Slider</a> by WOWSlider.com v4.7</span>
	<a href="#" class="ws_frame"></a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="wow-engine/wowslider.js"></script>
	<script type="text/javascript" src="wow-engine/script.js"></script>
<!-- End WOWSlider.com BODY section -->
